import { collection, doc, getDoc, getDocs, query, serverTimestamp, Timestamp, where, writeBatch } from "firebase/firestore";
import { auth, db } from "../lib/firebase";
import type { AppUser, Tender, TenderBid, TenderFinancialBid } from "../types";
import { calculateAboveBelowEstimate, rankFinancialBids } from "../utils/financialEvaluation";
import { getTenderBidsForTender } from "./tenderBidService";

function context(){if(!db||!auth?.currentUser)throw new Error("Firebase is not configured or the user is not signed in.");return{firestore:db,uid:auth.currentUser.uid};}
async function profile(){const{firestore,uid}=context();const snap=await getDoc(doc(firestore,"users",uid));if(!snap.exists())throw new Error("User profile not found.");return{uid,...snap.data()} as AppUser;}
const role=(p:AppUser)=>p.systemRole||p.role;
const assignedAgency=(p:AppUser,id:string)=>role(p)==="scert_admin"||(p.assignedAgencyIds?.includes(id)??false)||p.primaryAgencyId===id;
const mapFinancial=(snap:{id:string;data():unknown})=>({id:snap.id,...(snap.data() as Record<string,unknown>)} as TenderFinancialBid);
function isWithdrawn(b:TenderBid){return b.withdrawn===true||["withdrawn","withdrawn_before_financial_opening"].includes(b.status||"");}
export function isTechnicallyQualifiedBid(b:TenderBid){return b.qualified===true&&!isWithdrawn(b);}
async function tenderById(id:string){const{firestore}=context();const snap=await getDoc(doc(firestore,"tenders",id));return snap.exists()?({id:snap.id,...snap.data()} as Tender):null;}
function audit(batch:ReturnType<typeof writeBatch>,id:string,action:string,uid:string,previous:unknown,next:unknown,remarks=""){const{firestore}=context();batch.set(doc(collection(firestore,"auditLogs")),{entityType:"financial_evaluation",entityId:id,action,performedBy:uid,performedAt:serverTimestamp(),previousData:previous,newData:next,remarks});}
function openingDate(value:unknown){if(!value)return null;if(typeof value==="object"&&value&&"toDate" in value)return (value as{toDate():Date}).toDate();const d=new Date(String(value));return Number.isNaN(d.getTime())?null:d;}

export const getTenderBidsForFinancialEvaluation=(tenderId:string)=>getTenderBidsForTender(tenderId);
export async function getFinancialBidsForTender(tenderId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"tenderFinancialBids"),where("tenderId","==",tenderId)))).docs.map(mapFinancial);}
export async function getFinancialEvaluation(tenderId:string){const tender=await tenderById(tenderId);if(!tender)throw new Error("Tender not found.");const[bids,financialBids]=await Promise.all([getTenderBidsForFinancialEvaluation(tenderId),getFinancialBidsForTender(tenderId)]);return{tender,bids,qualifiedBids:bids.filter(isTechnicallyQualifiedBid),ineligibleBids:bids.filter(b=>!isTechnicallyQualifiedBid(b)),financialBids:rankFinancialBids(financialBids)};}

export type FinancialOpeningInput={confirmed:boolean;actualOpeningAt:string;bidsOpened:number;eProcReference?:string;remarks?:string;overrideReason?:string;};
export async function recordFinancialBidOpening(tenderId:string,input:FinancialOpeningInput){
 if(!input.confirmed)throw new Error("Confirm that financial bids were opened on eProc Punjab.");if(!input.actualOpeningAt)throw new Error("Actual financial bid opening date and time are required.");if(!Number.isInteger(input.bidsOpened)||input.bidsOpened<0)throw new Error("Financial bids opened must be a whole number of zero or greater.");const actual=new Date(input.actualOpeningAt);if(Number.isNaN(actual.getTime()))throw new Error("Enter a valid actual financial opening date and time.");
 const{firestore,uid}=context(),user=await profile(),tender=await tenderById(tenderId);if(!tender)throw new Error("Tender not found.");
 if(!assignedAgency(user,tender.executingAgencyId))throw new Error("You are not authorised to record financial opening for this tender.");if(tender.status==="cancelled")throw new Error("Financial opening cannot be recorded for a cancelled tender.");
 if(tender.technicalEvaluationStatus!=="approved")throw new Error("Technical evaluation must be approved before financial opening can be recorded.");
 const bids=await getTenderBidsForFinancialEvaluation(tenderId),qualified=bids.filter(isTechnicallyQualifiedBid);if(!qualified.length)throw new Error("No technically qualified bidders are available for financial evaluation.");if(input.bidsOpened>qualified.length)throw new Error("Financial bids opened cannot exceed technically qualified, non-withdrawn bidders.");if(input.bidsOpened!==qualified.length&&!input.remarks?.trim())throw new Error("Remarks are required when the financial opening count differs from the eligible bidder count.");
 const scheduled=openingDate(tender.financialBidOpeningDate);if((!scheduled||actual<scheduled)&&!input.overrideReason?.trim())throw new Error("A reason is required because the recorded opening is early or the scheduled date is missing.");
 const next={financialEvaluationStatus:"in_progress",financialBidOpeningRecorded:true,financialBidOpeningActualAt:Timestamp.fromDate(actual),financialBidOpeningRecordedBy:uid,financialBidOpeningRecordedAt:serverTimestamp(),financialBidOpeningSource:"eproc_punjab",financialBidOpeningBidCount:input.bidsOpened,eProcFinancialOpeningReference:input.eProcReference?.trim()||"",financialBidsOpenedBy:uid,financialBidsOpenedAt:serverTimestamp(),financialBidOpeningRemarks:input.remarks?.trim()||"",financialOpeningOverrideReason:input.overrideReason?.trim()||"",updatedBy:uid,updatedAt:serverTimestamp()};
 const batch=writeBatch(firestore);batch.update(doc(firestore,"tenders",tenderId),next);audit(batch,tenderId,"record_financial_bid_opening",uid,{financialBidOpeningRecorded:Boolean(tender.financialBidOpeningRecorded||tender.financialBidsOpenedAt)},next,input.overrideReason||input.remarks);await batch.commit();
}

export async function createOrUpdateFinancialBid(tenderId:string,tenderBidId:string,quotedAmount:number,remarks="",correctionReason=""){
 if(!Number.isFinite(quotedAmount)||quotedAmount<0)throw new Error("Quoted amount must be zero or greater.");
 const{firestore,uid}=context(),user=await profile(),tender=await tenderById(tenderId);if(!tender)throw new Error("Tender not found.");
 const admin=role(user)==="scert_admin";if(!assignedAgency(user,tender.executingAgencyId))throw new Error("You are not authorised to edit this financial evaluation.");
 if(!tender.financialBidOpeningRecorded&&!tender.financialBidsOpenedAt)throw new Error("Record the Financial Bid Opening from eProc Punjab before entering financial bid values.");
 if(!admin&&!["in_progress","revision_required"].includes(tender.financialEvaluationStatus||"not_started"))throw new Error("Financial entries are locked in the current review status.");
 const bid=(await getTenderBidsForFinancialEvaluation(tenderId)).find(x=>x.id===tenderBidId);if(!bid||!isTechnicallyQualifiedBid(bid))throw new Error("Only a technically qualified, non-withdrawn bidder may receive a financial amount.");
 const existing=(await getFinancialBidsForTender(tenderId)).find(x=>x.tenderBidId===tenderBidId);if(admin&&existing&&existing.finalEvaluatedAmount!==quotedAmount&&!correctionReason.trim())throw new Error("SCERT correction reason is required.");
 const calc=calculateAboveBelowEstimate(tender.estimatedTenderValue,quotedAmount),ref=existing?doc(firestore,"tenderFinancialBids",existing.id):doc(collection(firestore,"tenderFinancialBids"));
 const record={id:ref.id,tenderId,tenderNumber:tender.tenderNumber||tender.nitNumber||"",tenderBidId,contractorId:bid.contractorId,contractorCode:bid.contractorCode,contractorName:bid.contractorName,workPackageId:tender.workPackageId,dietId:tender.dietId,dietName:tender.dietName,executingAgencyId:tender.executingAgencyId,executingAgencyName:tender.executingAgencyName,tenderEstimatedValue:tender.estimatedTenderValue,quotedAmount,finalEvaluatedAmount:quotedAmount,amountDifferenceFromEstimate:calc.difference,percentAboveBelowEstimate:calc.percentDifference,isL1:false,isL2:false,isL3:false,isJointLowest:false,isSelectedForRecommendation:false,financialBidStatus:"entered",remarks:remarks.trim(),enteredBy:existing?.enteredBy||uid,enteredAt:existing?.enteredAt||serverTimestamp(),updatedBy:uid,updatedAt:serverTimestamp()};
 const batch=writeBatch(firestore);existing?batch.update(ref,record):batch.set(ref,record);audit(batch,ref.id,existing?(admin?"scert_financial_amount_corrected":"financial_amount_corrected"):"financial_bid_amount_entered",uid,existing||null,record,correctionReason||remarks);await batch.commit();await recalculateFinancialRankings(tenderId);
}

export async function recalculateFinancialRankings(tenderId:string){
 const{firestore,uid}=context(),items=await getFinancialBidsForTender(tenderId),ranked=rankFinancialBids(items),batch=writeBatch(firestore);
 for(const item of ranked)batch.update(doc(firestore,"tenderFinancialBids",item.id),{comparisonPosition:item.comparisonPosition,rank:item.rank,isL1:item.isL1,isL2:item.isL2,isL3:item.isL3,isJointLowest:item.isJointLowest,financialBidStatus:"under_comparison",updatedBy:uid,updatedAt:serverTimestamp()});
 audit(batch,tenderId,"financial_ranking_recalculated",uid,items.map(x=>({id:x.id,rank:x.rank,isL1:x.isL1})),ranked.map(x=>({id:x.id,rank:x.rank,isL1:x.isL1,isJointLowest:x.isJointLowest})));await batch.commit();return ranked;
}
export function validateFinancialEvaluation(qualified:TenderBid[],financial:TenderFinancialBid[]){const missing=qualified.filter(b=>!financial.some(f=>f.tenderBidId===b.id));if(missing.length)throw new Error(`Financial amounts are missing for ${missing.length} technically qualified bidder(s).`);if(financial.some(x=>x.finalEvaluatedAmount<0))throw new Error("Financial bid amounts must not be negative.");return rankFinancialBids(financial);}
export async function submitFinancialEvaluation(tenderId:string,tieAcknowledged=false){
 const{firestore,uid}=context(),user=await profile(),data=await getFinancialEvaluation(tenderId);if(!assignedAgency(user,data.tender.executingAgencyId))throw new Error("You are not authorised to submit this evaluation.");
 if(!["in_progress","revision_required"].includes(data.tender.financialEvaluationStatus||"not_started"))throw new Error("Financial evaluation is not editable.");
 const ranked=validateFinancialEvaluation(data.qualifiedBids,data.financialBids),tie=ranked.some(x=>x.isJointLowest);if(tie&&!tieAcknowledged)throw new Error("Acknowledge the joint-lowest bid warning before submission.");
 const next={financialEvaluationStatus:"submitted_for_review",financialTieAcknowledged:tieAcknowledged,financialEvaluationRevisionRemarks:"",updatedBy:uid,updatedAt:serverTimestamp()},batch=writeBatch(firestore);batch.update(doc(firestore,"tenders",tenderId),next);for(const item of ranked)batch.update(doc(firestore,"tenderFinancialBids",item.id),{financialBidStatus:"submitted_for_review"});audit(batch,tenderId,"financial_evaluation_submitted",uid,{status:data.tender.financialEvaluationStatus},next);await batch.commit();
}
export async function returnFinancialEvaluationForRevision(tenderId:string,remarks:string){if(!remarks.trim())throw new Error("Revision remarks are required.");const{firestore,uid}=context(),user=await profile(),tender=await tenderById(tenderId);if(role(user)!=="scert_admin"||!tender)throw new Error("SCERT Admin permission is required.");const next={financialEvaluationStatus:"revision_required",financialEvaluationRevisionRemarks:remarks.trim(),updatedBy:uid,updatedAt:serverTimestamp()},batch=writeBatch(firestore);batch.update(doc(firestore,"tenders",tenderId),next);for(const item of await getFinancialBidsForTender(tenderId))batch.update(doc(firestore,"tenderFinancialBids",item.id),{financialBidStatus:"revision_required"});audit(batch,tenderId,"financial_evaluation_returned",uid,{status:tender.financialEvaluationStatus},next,remarks);await batch.commit();}
export async function approveFinancialEvaluation(tenderId:string){const{firestore,uid}=context(),user=await profile(),data=await getFinancialEvaluation(tenderId);if(role(user)!=="scert_admin")throw new Error("SCERT Admin permission is required.");if(data.tender.technicalEvaluationStatus!=="approved"||data.tender.financialEvaluationStatus!=="submitted_for_review")throw new Error("The evaluation is not ready for approval.");const ranked=validateFinancialEvaluation(data.qualifiedBids,data.financialBids);if(ranked.some(x=>x.isJointLowest)&&!data.tender.financialTieAcknowledged)throw new Error("Joint-lowest bid warning must be acknowledged.");const next={financialEvaluationStatus:"approved",financialEvaluationApprovedBy:uid,financialEvaluationApprovedAt:serverTimestamp(),updatedBy:uid,updatedAt:serverTimestamp()},batch=writeBatch(firestore);batch.update(doc(firestore,"tenders",tenderId),next);for(const item of ranked)batch.update(doc(firestore,"tenderFinancialBids",item.id),{financialBidStatus:"approved"});audit(batch,tenderId,"financial_evaluation_approved",uid,{status:data.tender.financialEvaluationStatus},next);await batch.commit();}
export async function generateComparativeStatement(tenderId:string){const data=await getFinancialEvaluation(tenderId),ranked=rankFinancialBids(data.financialBids),lowest=ranked[0]||null;return{...data,bidders:ranked,lowestBid:lowest,highestBid:ranked[ranked.length-1]||null,tieStatus:ranked.some(x=>x.isJointLowest),summary:{financialBasis:data.tender.estimatedTenderValue,bidCount:ranked.length,lowestAmount:lowest?.finalEvaluatedAmount||0}};}
