import { arrayUnion, collection, doc, getDoc, getDocs, query, serverTimestamp, where, writeBatch } from "firebase/firestore";
import { auth, db, getFirebaseConfigurationMessage } from "../lib/firebase";
import { getActivityMaster } from "../lib/firestore";
import { getDietActivityFinancials } from "./dietActivityFinancialService";
import type { DietAgencyAssignment, ScopeCategory, ScopeOfWork, ScopeOfWorkStatus } from "../types";

export type ScopeOfWorkInput = { assignment: DietAgencyAssignment; scopeTitle: string; scopeDescription: string; functionalRequirement?:string;siteConditionNotes?:string;drawingRequirement?:ScopeOfWork["drawingRequirement"];scopeCategories: ScopeCategory[]; activityIds: string[]; remarks?: string };
function context(){if(!db)throw new Error(getFirebaseConfigurationMessage());if(!auth?.currentUser)throw new Error("You must be signed in.");return{firestore:db,uid:auth.currentUser.uid};}
const mapScope=(item:{id:string;data():unknown})=>({...item.data() as object,id:item.id}) as ScopeOfWork;
export async function getScopeOfWorks(){const{firestore}=context();return(await getDocs(collection(firestore,"scopeOfWorks"))).docs.map(mapScope);}
export async function getScopesForDiet(dietId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"scopeOfWorks"),where("dietId","==",dietId)))).docs.map(mapScope);}
export async function getScopesForAgency(agencyId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"scopeOfWorks"),where("executingAgencyId","==",agencyId)))).docs.map(mapScope);}
export async function getScopesForArchitecture(dietIds:string[]){const groups=await Promise.all(dietIds.map(getScopesForDiet));return groups.flat().filter(scope=>["sent_to_architecture","architecture_review","architecture_revision_requested","architectural_drawings_issued","diet_drawing_review","drawing_revision_requested","diet_drawing_accepted","submitted_to_scert_for_drawing_approval","scert_drawing_review","scert_drawing_revision_required","architectural_drawings_approved"].includes(scope.status));}
export async function getScopeOfWork(id:string){const{firestore}=context();const item=await getDoc(doc(firestore,"scopeOfWorks",id));return item.exists()?mapScope(item):null;}
function validate(input:ScopeOfWorkInput){if(input.assignment.status!=="active")throw new Error("Select an active executing-agency assignment.");if(!input.scopeTitle.trim()||!input.scopeDescription.trim())throw new Error("Scope title and description are required.");if(!input.scopeCategories.length)throw new Error("Select at least one scope category.");if(!input.activityIds.length)throw new Error("Select at least one activity.");}
async function validateActivities(dietId:string,activityIds:string[]){const[master,financials]=await Promise.all([getActivityMaster(),getDietActivityFinancials([dietId])]);const activeMaster=new Set(master.filter(x=>x.active!==false).map(x=>x.id)),byActivity=new Map(financials.filter(x=>x.active!==false&&x.activityId).map(x=>[x.activityId,x]));for(const id of activityIds){if(!activeMaster.has(id))throw new Error("A selected activity does not exist in the active Activity Master.");const financial=byActivity.get(id);if(!financial)throw new Error("A selected activity has no active DIET financial approval.");if(financial.agencyAllocation<=0)throw new Error(`${financial.activityName} is Principal-only and cannot be included in an agency Scope.`);}}
async function currentRole(){const{firestore,uid}=context(),snap=await getDoc(doc(firestore,"users",uid));return String(snap.data()?.systemRole||snap.data()?.role||"");}
function data(input:ScopeOfWorkInput){return{dietId:input.assignment.dietId,dietName:input.assignment.dietName,phaseId:input.assignment.phaseId||"",phaseName:input.assignment.phaseName||"",dietAgencyAssignmentId:input.assignment.id,executingAgencyId:input.assignment.executingAgencyId,executingAgencyName:input.assignment.executingAgencyName,scopeTitle:input.scopeTitle.trim(),scopeDescription:input.scopeDescription.trim(),functionalRequirement:input.functionalRequirement?.trim()||input.scopeDescription.trim(),siteConditionNotes:input.siteConditionNotes?.trim()||"",drawingRequirement:input.drawingRequirement||"architectural_required",scopeCategories:[...new Set(input.scopeCategories)],activityIds:[...new Set(input.activityIds)],remarks:input.remarks?.trim()||""};}
export async function createScopeOfWork(input:ScopeOfWorkInput){if(await currentRole()!=="diet_nodal_officer")throw new Error("Only the assigned DIET Nodal Officer can prepare a Scope.");validate(input);await validateActivities(input.assignment.dietId,input.activityIds);const{firestore,uid}=context(),ref=doc(collection(firestore,"scopeOfWorks")),record={id:ref.id,...data(input),scopeRevision:1,status:"draft",preparedBy:uid,preparedAt:serverTimestamp(),updatedBy:uid,updatedAt:serverTimestamp()};const batch=writeBatch(firestore);batch.set(ref,record);batch.set(doc(collection(firestore,"auditLogs")),{entityType:"scopeOfWork",entityId:ref.id,action:"scope_created",performedBy:uid,performedAt:serverTimestamp(),previousData:null,newData:record,remarks:record.remarks});await batch.commit();return ref.id;}
export async function updateScopeOfWork(id:string,input:ScopeOfWorkInput){if(await currentRole()!=="diet_nodal_officer")throw new Error("Only DIET can revise a Scope.");validate(input);await validateActivities(input.assignment.dietId,input.activityIds);const{firestore,uid}=context(),ref=doc(firestore,"scopeOfWorks",id),previous=await getDoc(ref);if(!previous.exists()||!["draft","architecture_revision_requested","revision_requested","revision_required"].includes(previous.data().status))throw new Error("This Scope is not editable by DIET.");const next={...data(input),scopeRevision:Number(previous.data().scopeRevision||1)+(previous.data().status==="draft"?0:1),status:previous.data().status==="draft"?"draft":"architecture_revision_requested",updatedBy:uid,updatedAt:serverTimestamp()};const batch=writeBatch(firestore);batch.update(ref,next);batch.set(doc(collection(firestore,"auditLogs")),{entityType:"scopeOfWork",entityId:id,action:"scope_updated",performedBy:uid,performedAt:serverTimestamp(),previousData:previous.data(),newData:next,remarks:next.remarks});await batch.commit();}
async function handshakeTransition(id:string,allowed:ScopeOfWorkStatus[],status:ScopeOfWorkStatus,action:string,comment="",fields:Record<string,unknown>={}){const{firestore,uid}=context(),ref=doc(firestore,"scopeOfWorks",id),previous=await getDoc(ref);if(!previous.exists()||!allowed.includes(previous.data().status))throw new Error("Scope is not in the required status for this action.");const r=await currentRole(),entry=comment.trim()?{comment:comment.trim(),commentBy:uid,role:r,timestamp:new Date(),revision:Number(previous.data().reviewHistory?.length||0)+1,action}:null,next={status,...fields,updatedBy:uid,updatedAt:serverTimestamp(),...(entry?{reviewHistory:arrayUnion(entry)}:{})};const batch=writeBatch(firestore);batch.update(ref,next);batch.set(doc(collection(firestore,"auditLogs")),{entityType:"scopeOfWork",entityId:id,action,performedBy:uid,performedAt:serverTimestamp(),previousData:previous.data(),newData:next,remarks:comment.trim()});await batch.commit();}
export async function sendScopeToAgency(id:string){if(await currentRole()!=="diet_nodal_officer")throw new Error("Only DIET can send the Scope to the Agency.");const scope=await getScopeOfWork(id);if(!scope)throw new Error("Scope not found.");await validateActivities(scope.dietId,scope.activityIds);const{uid}=context();return handshakeTransition(id,["draft","revision_requested","revision_required"],"sent_to_agency","scope_sent_to_agency","",{sentToAgencyBy:uid,sentToAgencyAt:serverTimestamp(),agencyReviewStatus:"pending"});}
export async function startAgencyScopeReview(id:string){if(await currentRole()!=="agency_user")throw new Error("Only the assigned Agency can review this Scope.");return handshakeTransition(id,["sent_to_agency"],"agency_review","scope_agency_review_started");}
export async function requestAgencyScopeRevision(id:string,comment:string){if(!comment.trim())throw new Error("Agency revision comments are required.");if(await currentRole()!=="agency_user")throw new Error("Only the assigned Agency can request revision.");const{uid}=context();return handshakeTransition(id,["sent_to_agency","agency_review"],"revision_requested","scope_revision_requested",comment,{agencyReviewStatus:"revision_requested",agencyReviewedBy:uid,agencyReviewedAt:serverTimestamp(),agencyComments:comment.trim()});}
export async function acceptScopeByAgency(id:string,comment=""){if(await currentRole()!=="agency_user")throw new Error("Only the assigned Agency can accept this Scope.");const{uid}=context();return handshakeTransition(id,["sent_to_agency","agency_review"],"agency_accepted","scope_agency_accepted",comment,{agencyReviewStatus:"accepted",agencyReviewedBy:uid,agencyReviewedAt:serverTimestamp(),agencyComments:comment.trim(),agencyAcceptedBy:uid,agencyAcceptedAt:serverTimestamp()});}
export async function confirmScopeMutualAgreement(id:string){if(await currentRole()!=="diet_nodal_officer")throw new Error("Only DIET can confirm mutual agreement.");const{uid}=context();return handshakeTransition(id,["agency_accepted"],"mutually_agreed","scope_mutually_agreed","",{dietAgreedBy:uid,dietAgreedAt:serverTimestamp(),mutualAgreementCompletedAt:serverTimestamp()});}
export async function sendScopeToArchitecture(id:string){if(await currentRole()!=="diet_nodal_officer")throw new Error("Only DIET can send a Scope to Architecture.");const scope=await getScopeOfWork(id);if(!scope)throw new Error("Scope not found.");await validateActivities(scope.dietId,scope.activityIds);const{firestore,uid}=context();if(scope.drawingRequirement==="not_required")return handshakeTransition(id,["draft","architecture_revision_requested"],"released_to_executing_agency","scope_released_to_agency","No architectural drawing required.",{releasedToAgencyBy:uid,releasedToAgencyAt:serverTimestamp()});const assignments=await getDocs(query(collection(firestore,"users"),where("assignedDietIds","array-contains",scope.dietId),where("systemRole","==","architecture_user"),where("active","==",true),where("approvalStatus","==","approved")));if(!assignments.docs.some(item=>item.data().active===true&&item.data().systemRole==="architecture_user"))throw new Error("No Architecture Department user has been allotted to this DIET by SCERT.");return handshakeTransition(id,["draft","architecture_revision_requested"],"sent_to_architecture","scope_sent_to_architecture","",{sentToArchitectureBy:uid,sentToArchitectureAt:serverTimestamp(),scopeRevision:Number(scope.scopeRevision||1)});}
export async function startArchitectureReview(id:string){if(await currentRole()!=="architecture_user")throw new Error("Architecture Department permission is required.");return handshakeTransition(id,["sent_to_architecture"],"architecture_review","architecture_review_started");}
export async function requestArchitectureScopeRevision(id:string,comment:string){if(!comment.trim())throw new Error("Clarification comments are required.");if(await currentRole()!=="architecture_user")throw new Error("Architecture Department permission is required.");return handshakeTransition(id,["sent_to_architecture","architecture_review"],"architecture_revision_requested","architecture_scope_revision_requested",comment);}
export async function requestDrawingRevision(id:string,comment:string){if(!comment.trim())throw new Error("Drawing revision comments are required.");if(await currentRole()!=="diet_nodal_officer")throw new Error("Only DIET can request drawing revision.");return handshakeTransition(id,["diet_drawing_review"],"drawing_revision_requested","diet_drawing_revision_requested",comment,{dietAcceptedDrawingRevision:"",scertApprovedDrawingRevision:""});}
export async function acceptArchitecturalDrawings(id:string){if(await currentRole()!=="diet_nodal_officer")throw new Error("Only DIET can accept drawings.");const scope=await getScopeOfWork(id);if(!scope?.currentDrawingRevision)throw new Error("No issued drawing revision is available.");const{uid}=context();return handshakeTransition(id,["diet_drawing_review"],"diet_drawing_accepted","diet_architectural_drawings_accepted","",{dietAcceptedDrawingRevision:scope.currentDrawingRevision,dietDrawingAcceptedBy:uid,dietDrawingAcceptedAt:serverTimestamp()});}
export async function submitDrawingsToScert(id:string){if(await currentRole()!=="diet_nodal_officer")throw new Error("Only DIET can submit drawings to SCERT.");const scope=await getScopeOfWork(id);if(!scope?.currentDrawingRevision||scope.dietAcceptedDrawingRevision!==scope.currentDrawingRevision)throw new Error("DIET acceptance must match the current drawing revision.");return handshakeTransition(id,["diet_drawing_accepted"],"submitted_to_scert_for_drawing_approval","architectural_drawings_submitted_to_scert");}
export async function startScertDrawingReview(id:string){if(await currentRole()!=="scert_admin")throw new Error("SCERT Admin permission is required.");return handshakeTransition(id,["submitted_to_scert_for_drawing_approval"],"scert_drawing_review","scert_drawing_review_started");}
export async function returnScertDrawingRevision(id:string,comment:string){if(!comment.trim())throw new Error("SCERT drawing revision comments are required.");if(await currentRole()!=="scert_admin")throw new Error("SCERT Admin permission is required.");return handshakeTransition(id,["submitted_to_scert_for_drawing_approval","scert_drawing_review"],"scert_drawing_revision_required","scert_drawing_revision_required",comment,{dietAcceptedDrawingRevision:"",scertApprovedDrawingRevision:""});}
export async function approveArchitecturalDrawings(id:string){if(await currentRole()!=="scert_admin")throw new Error("SCERT Admin permission is required.");const scope=await getScopeOfWork(id);if(!scope?.currentDrawingRevision||scope.dietAcceptedDrawingRevision!==scope.currentDrawingRevision)throw new Error("DIET acceptance does not match the current drawing revision.");const{uid}=context();return handshakeTransition(id,["submitted_to_scert_for_drawing_approval","scert_drawing_review"],"architectural_drawings_approved","scert_architectural_drawings_approved","",{scertApprovedDrawingRevision:scope.currentDrawingRevision,scertDrawingApprovedBy:uid,scertDrawingApprovedAt:serverTimestamp()});}
export async function releaseScopeToAgency(id:string){if(await currentRole()!=="scert_admin")throw new Error("SCERT Admin permission is required.");const scope=await getScopeOfWork(id);if(!scope?.currentDrawingRevision||scope.dietAcceptedDrawingRevision!==scope.currentDrawingRevision||scope.scertApprovedDrawingRevision!==scope.currentDrawingRevision)throw new Error("DIET acceptance and SCERT approval must match the current drawing revision.");const{uid}=context();return handshakeTransition(id,["architectural_drawings_approved"],"released_to_executing_agency","scope_released_to_agency","",{releasedToAgencyBy:uid,releasedToAgencyAt:serverTimestamp()});}
