import { collection, doc, getDoc, getDocs, query, serverTimestamp, where, writeBatch } from "firebase/firestore";
import { auth, db, getFirebaseConfigurationMessage } from "../lib/firebase";
import type { DietAgencyAssignment, ScopeCategory, ScopeOfWork, ScopeOfWorkStatus } from "../types";

export type ScopeOfWorkInput = { assignment: DietAgencyAssignment; scopeTitle: string; scopeDescription: string; scopeCategories: ScopeCategory[]; activityIds: string[]; remarks?: string };
function context(){if(!db)throw new Error(getFirebaseConfigurationMessage());if(!auth?.currentUser)throw new Error("You must be signed in.");return{firestore:db,uid:auth.currentUser.uid};}
const mapScope=(item:{id:string;data():unknown})=>({...item.data() as object,id:item.id}) as ScopeOfWork;
export async function getScopeOfWorks(){const{firestore}=context();return(await getDocs(collection(firestore,"scopeOfWorks"))).docs.map(mapScope);}
export async function getScopesForDiet(dietId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"scopeOfWorks"),where("dietId","==",dietId)))).docs.map(mapScope);}
export async function getScopesForAgency(agencyId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"scopeOfWorks"),where("executingAgencyId","==",agencyId)))).docs.map(mapScope);}
export async function getScopeOfWork(id:string){const{firestore}=context();const item=await getDoc(doc(firestore,"scopeOfWorks",id));return item.exists()?mapScope(item):null;}
function validate(input:ScopeOfWorkInput){if(input.assignment.status!=="active")throw new Error("Select an active executing-agency assignment.");if(!input.scopeTitle.trim()||!input.scopeDescription.trim())throw new Error("Scope title and description are required.");if(!input.scopeCategories.length)throw new Error("Select at least one scope category.");if(!input.activityIds.length)throw new Error("Select at least one activity.");}
function data(input:ScopeOfWorkInput){return{dietId:input.assignment.dietId,dietName:input.assignment.dietName,phaseId:input.assignment.phaseId||"",phaseName:input.assignment.phaseName||"",dietAgencyAssignmentId:input.assignment.id,executingAgencyId:input.assignment.executingAgencyId,executingAgencyName:input.assignment.executingAgencyName,scopeTitle:input.scopeTitle.trim(),scopeDescription:input.scopeDescription.trim(),scopeCategories:[...new Set(input.scopeCategories)],activityIds:[...new Set(input.activityIds)],remarks:input.remarks?.trim()||""};}
export async function createScopeOfWork(input:ScopeOfWorkInput){validate(input);const{firestore,uid}=context(),ref=doc(collection(firestore,"scopeOfWorks")),record={id:ref.id,...data(input),status:"draft",preparedBy:uid,preparedAt:serverTimestamp(),updatedBy:uid,updatedAt:serverTimestamp()};const batch=writeBatch(firestore);batch.set(ref,record);batch.set(doc(collection(firestore,"auditLogs")),{entityType:"scopeOfWork",entityId:ref.id,action:"scope_created",performedBy:uid,performedAt:serverTimestamp(),previousData:null,newData:record,remarks:record.remarks});await batch.commit();return ref.id;}
export async function updateScopeOfWork(id:string,input:ScopeOfWorkInput){validate(input);const{firestore,uid}=context(),ref=doc(firestore,"scopeOfWorks",id),previous=await getDoc(ref);if(!previous.exists())throw new Error("Scope not found.");const next={...data(input),updatedBy:uid,updatedAt:serverTimestamp()};const batch=writeBatch(firestore);batch.update(ref,next);batch.set(doc(collection(firestore,"auditLogs")),{entityType:"scopeOfWork",entityId:id,action:"scope_updated",performedBy:uid,performedAt:serverTimestamp(),previousData:previous.data(),newData:next,remarks:next.remarks});await batch.commit();}
async function transition(id:string,allowed:ScopeOfWorkStatus[],status:ScopeOfWorkStatus,action:string,remarks=""){const{firestore,uid}=context(),ref=doc(firestore,"scopeOfWorks",id),previous=await getDoc(ref);if(!previous.exists()||!allowed.includes(previous.data().status))throw new Error("Scope is not in the required status for this action.");const next:Record<string,unknown>={status,remarks:remarks.trim()||previous.data().remarks||"",updatedBy:uid,updatedAt:serverTimestamp()};if(status==="submitted")Object.assign(next,{reviewedBy:"",reviewedAt:null});if(status==="under_review")Object.assign(next,{reviewedBy:uid,reviewedAt:serverTimestamp()});if(status==="approved")Object.assign(next,{approvedBy:uid,approvedAt:serverTimestamp()});const batch=writeBatch(firestore);batch.update(ref,next);batch.set(doc(collection(firestore,"auditLogs")),{entityType:"scopeOfWork",entityId:id,action,performedBy:uid,performedAt:serverTimestamp(),previousData:previous.data(),newData:next,remarks:remarks.trim()});await batch.commit();}
export const submitScopeOfWork=(id:string)=>transition(id,["draft","revision_required"],"submitted","scope_submitted");
export const reviewScopeOfWork=(id:string)=>transition(id,["submitted"],"under_review","scope_review_started");
export const approveScopeOfWork=(id:string)=>transition(id,["submitted","under_review"],"approved","scope_approved");
export const returnScopeForRevision=(id:string,remarks:string)=>{if(!remarks.trim())throw new Error("Revision remarks are required.");return transition(id,["submitted","under_review"],"revision_required","scope_returned_for_revision",remarks);};
