import { collection, doc, getDoc, getDocs, query, serverTimestamp, Timestamp, where, writeBatch } from "firebase/firestore";
import { auth, db } from "../lib/firebase";
import type { AppUser, CorrigendumType, Tender, TenderCorrigendum } from "../types";

function context(){if(!db||!auth?.currentUser)throw new Error("Firebase is not configured or the user is not signed in.");return{firestore:db,uid:auth.currentUser.uid};}
const role=(u:AppUser)=>u.systemRole||u.role;
async function profile(){const{firestore,uid}=context(),snap=await getDoc(doc(firestore,"users",uid));if(!snap.exists())throw new Error("User profile not found.");return{uid,...snap.data()} as AppUser;}
const assigned=(u:AppUser,id:string)=>role(u)==="scert_admin"||(role(u)==="agency_user"&&((u.assignedAgencyIds||[]).includes(id)||u.primaryAgencyId===id));
const date=(value:string)=>value?Timestamp.fromDate(new Date(`${value}T00:00:00`)):null;
export async function getTenderCorrigenda(tenderId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"tenderCorrigenda"),where("tenderId","==",tenderId)))).docs.map(s=>({id:s.id,...s.data()} as TenderCorrigendum));}
export type CorrigendumInput={corrigendumNumber?:string;corrigendumTitle:string;corrigendumType:CorrigendumType;issueDate:string;description:string;revisedBidSubmissionEndDate?:string;revisedTechnicalOpeningDate?:string;revisedFinancialOpeningDate?:string;eProcReference?:string;eProcUrl?:string;remarks?:string;};
export async function recordTenderCorrigendum(tenderId:string,input:CorrigendumInput){if(!input.corrigendumTitle.trim()||!input.issueDate||!input.description.trim())throw new Error("Corrigendum title, issue date and description are required.");const{firestore,uid}=context(),user=await profile(),tenderRef=doc(firestore,"tenders",tenderId),snap=await getDoc(tenderRef);if(!snap.exists())throw new Error("Tender not found.");const tender={id:snap.id,...snap.data()} as Tender;if(tender.status!=="published"||!assigned(user,tender.executingAgencyId))throw new Error("You are not authorised to record a corrigendum for this published tender.");const ref=doc(collection(firestore,"tenderCorrigenda")),record={id:ref.id,tenderId,tenderNumber:tender.tenderNumber||tender.nitNumber||"",dietId:tender.dietId,executingAgencyId:tender.executingAgencyId,corrigendumNumber:input.corrigendumNumber?.trim()||"",corrigendumTitle:input.corrigendumTitle.trim(),corrigendumType:input.corrigendumType,issueDate:date(input.issueDate),description:input.description.trim(),previousBidSubmissionEndDate:tender.bidSubmissionEndDate||null,revisedBidSubmissionEndDate:date(input.revisedBidSubmissionEndDate||""),previousTechnicalOpeningDate:tender.technicalBidOpeningDate||null,revisedTechnicalOpeningDate:date(input.revisedTechnicalOpeningDate||""),previousFinancialOpeningDate:tender.financialBidOpeningDate||null,revisedFinancialOpeningDate:date(input.revisedFinancialOpeningDate||""),eProcReference:input.eProcReference?.trim()||"",eProcUrl:input.eProcUrl?.trim()||"",recordedBy:uid,recordedAt:serverTimestamp(),remarks:input.remarks?.trim()||""};const update:Record<string,unknown>={updatedBy:uid,updatedAt:serverTimestamp()};if(input.revisedBidSubmissionEndDate)update.bidSubmissionEndDate=record.revisedBidSubmissionEndDate;if(input.revisedTechnicalOpeningDate)update.technicalBidOpeningDate=record.revisedTechnicalOpeningDate;if(input.revisedFinancialOpeningDate)update.financialBidOpeningDate=record.revisedFinancialOpeningDate;const batch=writeBatch(firestore);batch.set(ref,record);batch.update(tenderRef,update);batch.set(doc(collection(firestore,"auditLogs")),{entityType:"tender_corrigendum",entityId:ref.id,action:"record_corrigendum",performedBy:uid,performedAt:serverTimestamp(),previousData:null,newData:record,remarks:record.remarks});await batch.commit();return ref.id;}
