import { collection, doc, getDoc, getDocs, query, serverTimestamp, where, writeBatch } from "firebase/firestore";
import { auth, db } from "../lib/firebase";
import type { AppUser, Tender, TenderAward, TenderAwardRecommendation, TenderFinancialBid } from "../types";
import { getContractorById } from "./contractorService";
import { generateComparativeStatement } from "./financialEvaluationService";
import { calculateTenderAwardVariance } from "../utils/tenderAward";

function context(){if(!db||!auth?.currentUser)throw new Error("Firebase is not configured or the user is not signed in.");return{firestore:db,uid:auth.currentUser.uid};}
async function profile(){const{firestore,uid}=context();const s=await getDoc(doc(firestore,"users",uid));if(!s.exists())throw new Error("User profile not found.");return{uid,...s.data()} as AppUser;}
const role=(p:AppUser)=>p.systemRole||p.role;
const assigned=(p:AppUser,id:string)=>role(p)==="scert_admin"||p.primaryAgencyId===id||Boolean(p.assignedAgencyIds?.includes(id));
const mapRec=(s:{id:string;data():unknown})=>({id:s.id,...(s.data() as Record<string,unknown>)} as TenderAwardRecommendation);
const mapAward=(s:{id:string;data():unknown})=>({id:s.id,...(s.data() as Record<string,unknown>)} as TenderAward);
function audit(batch:ReturnType<typeof writeBatch>,type:string,id:string,action:string,uid:string,previous:unknown,next:unknown,remarks=""){const{firestore}=context();batch.set(doc(collection(firestore,"auditLogs")),{entityType:type,entityId:id,action,performedBy:uid,performedAt:serverTimestamp(),previousData:previous,newData:next,remarks});}
async function tender(id:string){const{firestore}=context(),s=await getDoc(doc(firestore,"tenders",id));return s.exists()?({id:s.id,...s.data()} as Tender):null;}

export async function getAwardRecommendations(){const{firestore}=context();return(await getDocs(collection(firestore,"tenderAwardRecommendations"))).docs.map(mapRec);}
export async function getAwardRecommendationsForTender(tenderId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"tenderAwardRecommendations"),where("tenderId","==",tenderId)))).docs.map(mapRec);}
export async function getAwardRecommendationById(id:string){const{firestore}=context(),s=await getDoc(doc(firestore,"tenderAwardRecommendations",id));return s.exists()?mapRec(s):null;}
export async function getTenderAwards(){const{firestore}=context();return(await getDocs(collection(firestore,"tenderAwards"))).docs.map(mapAward);}
export async function getTenderAwardsForAgency(executingAgencyId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"tenderAwards"),where("executingAgencyId","==",executingAgencyId)))).docs.map(mapAward);}
export async function getTenderAwardsForDiet(dietId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"tenderAwards"),where("dietId","==",dietId)))).docs.map(mapAward);}
export async function getAwardRecommendationsForAgency(executingAgencyId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"tenderAwardRecommendations"),where("executingAgencyId","==",executingAgencyId)))).docs.map(mapRec);}
export async function getAwardRecommendationsForDiet(dietId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"tenderAwardRecommendations"),where("dietId","==",dietId)))).docs.map(mapRec);}
export async function getTenderAwardsForTender(tenderId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"tenderAwards"),where("tenderId","==",tenderId)))).docs.map(mapAward);}
export async function getTenderAwardById(id:string){const{firestore}=context(),s=await getDoc(doc(firestore,"tenderAwards",id));return s.exists()?mapAward(s):null;}

export type RecommendationInput={financialBid:TenderFinancialBid;proposedAwardAmount:number;recommendationReason:string;nonL1Justification?:string;jointL1Justification?:string;};
export async function createAwardRecommendation(tenderId:string,input:RecommendationInput,existingId?:string){
 if(!Number.isFinite(input.proposedAwardAmount)||input.proposedAwardAmount<0)throw new Error("Proposed award amount must be zero or greater.");
 if(!input.recommendationReason.trim())throw new Error("Recommendation reason is required.");
 const{firestore,uid}=context(),user=await profile(),data=await generateComparativeStatement(tenderId),t=data.tender;
 if(t.financialEvaluationStatus!=="approved")throw new Error("Financial evaluation must be approved before tender award can be initiated.");
 if(["cancelled","retender_required"].includes(t.status))throw new Error("A cancelled or re-tendered tender cannot be recommended.");
 if(!assigned(user,t.executingAgencyId))throw new Error("You are not authorised for this executing agency.");
 const selected=data.bidders.find(x=>x.id===input.financialBid.id);if(!selected)throw new Error("The selected financial bidder does not belong to this tender.");
 const isLowest=selected.rank===1||selected.isJointLowest===true;if(!isLowest&&!input.nonL1Justification?.trim())throw new Error("Reason for recommending a bidder other than L1 is required.");
 if(selected.isJointLowest&&!input.jointL1Justification?.trim())throw new Error("Joint L1 selection justification is required.");
 const contractor=await getContractorById(selected.contractorId);if(!contractor)throw new Error("Contractor master record not found.");if(contractor.blacklisted)throw new Error("The recommended contractor is currently blacklisted.");if(!contractor.active)throw new Error("The recommended contractor is currently inactive.");
 const old=existingId?await getAwardRecommendationById(existingId):null;if(old&&!["draft","revision_required"].includes(old.status)&&role(user)!=="scert_admin")throw new Error("Submitted recommendations are locked.");
 const ref=old?doc(firestore,"tenderAwardRecommendations",old.id):doc(collection(firestore,"tenderAwardRecommendations"));
 const record={id:ref.id,tenderId,tenderNumber:t.tenderNumber||t.nitNumber||"",workPackageId:t.workPackageId,dietId:t.dietId,dietName:t.dietName,executingAgencyId:t.executingAgencyId,executingAgencyName:t.executingAgencyName,recommendedTenderBidId:selected.tenderBidId,recommendedFinancialBidId:selected.id,contractorId:selected.contractorId,contractorCode:selected.contractorCode,contractorName:selected.contractorName,financialRank:selected.rank||null,isL1:selected.isL1===true,tenderEstimatedValue:t.estimatedTenderValue,quotedAmount:selected.quotedAmount,evaluatedAmount:selected.finalEvaluatedAmount,proposedAwardAmount:input.proposedAwardAmount,recommendationReason:input.recommendationReason.trim(),nonL1Justification:input.nonL1Justification?.trim()||"",jointL1Justification:input.jointL1Justification?.trim()||"",status:old?.status==="revision_required"?"revision_required":"draft",recommendedBy:old?.recommendedBy||uid,recommendedAt:old?.recommendedAt||serverTimestamp(),updatedBy:uid,updatedAt:serverTimestamp(),reviewedBy:old?.reviewedBy||"",reviewedAt:old?.reviewedAt||null,scertRemarks:old?.scertRemarks||""};
 const batch=writeBatch(firestore);old?batch.update(ref,record):batch.set(ref,record);batch.update(doc(firestore,"tenders",tenderId),{awardStatus:"recommendation_pending",updatedBy:uid,updatedAt:serverTimestamp()});audit(batch,"tender_award_recommendation",ref.id,old?"award_recommendation_updated":"award_recommendation_created",uid,old,record,record.nonL1Justification||record.recommendationReason);await batch.commit();return ref.id;
}
export async function submitAwardRecommendation(id:string){const{firestore,uid}=context(),user=await profile(),rec=await getAwardRecommendationById(id);if(!rec||!assigned(user,rec.executingAgencyId)||!["draft","revision_required"].includes(rec.status))throw new Error("Recommendation cannot be submitted.");const contractor=await getContractorById(rec.contractorId);if(!contractor?.active||contractor.blacklisted)throw new Error(contractor?.blacklisted?"The recommended contractor is currently blacklisted.":"The recommended contractor is currently inactive.");const t=await tender(rec.tenderId);if(t?.financialEvaluationStatus!=="approved")throw new Error("Financial evaluation must be approved before submission.");const next={status:"submitted_to_scert",recommendedBy:uid,recommendedAt:serverTimestamp(),updatedBy:uid,updatedAt:serverTimestamp()},batch=writeBatch(firestore);batch.update(doc(firestore,"tenderAwardRecommendations",id),next);audit(batch,"tender_award_recommendation",id,"award_recommendation_submitted",uid,{status:rec.status},next);await batch.commit();}
async function scertDecision(id:string,status:"revision_required"|"approved"|"rejected",remarks:string){if(status!=="approved"&&!remarks.trim())throw new Error("SCERT remarks are required.");const{firestore,uid}=context(),user=await profile(),rec=await getAwardRecommendationById(id);if(role(user)!=="scert_admin"||!rec||rec.status!=="submitted_to_scert")throw new Error("SCERT Admin review permission is required.");const next={status,reviewedBy:uid,reviewedAt:serverTimestamp(),scertRemarks:remarks.trim(),updatedBy:uid,updatedAt:serverTimestamp()},batch=writeBatch(firestore);batch.update(doc(firestore,"tenderAwardRecommendations",id),next);if(status==="approved")batch.update(doc(firestore,"tenders",rec.tenderId),{awardStatus:"recommendation_approved",updatedBy:uid,updatedAt:serverTimestamp()});audit(batch,"tender_award_recommendation",id,status==="approved"?"award_recommendation_approved":status==="rejected"?"award_recommendation_rejected":"award_recommendation_returned",uid,{status:rec.status},next,remarks);await batch.commit();}
export const returnAwardRecommendationForRevision=(id:string,remarks:string)=>scertDecision(id,"revision_required",remarks);
export const approveAwardRecommendation=(id:string,remarks="")=>scertDecision(id,"approved",remarks);
export const rejectAwardRecommendation=(id:string,remarks:string)=>scertDecision(id,"rejected",remarks);

export async function createTenderAward(recommendationId:string,input:{awardNumber:string;awardDate:string;finalContractValue:number;remarks?:string}){
 if(!input.awardNumber.trim()||!input.awardDate)throw new Error("Award Number and Award Date are required.");if(!Number.isFinite(input.finalContractValue)||input.finalContractValue<0)throw new Error("Final contract value must be zero or greater.");
 const{firestore,uid}=context(),user=await profile(),rec=await getAwardRecommendationById(recommendationId);if(role(user)!=="scert_admin"||!rec||rec.status!=="approved")throw new Error("An approved SCERT recommendation is required.");
 if(await getTenderAwardsForTender(rec.tenderId).then(x=>x.some(a=>a.status!=="cancelled")))throw new Error("An active tender award already exists.");
 if(input.finalContractValue>rec.tenderEstimatedValue&&!input.remarks?.trim())throw new Error("Remarks are required when final contract value is above the tender estimate.");
 const{firestore:store}=context(),variance=calculateTenderAwardVariance(rec.tenderEstimatedValue,input.finalContractValue),wpSnap=await getDoc(doc(store,"workPackages",rec.workPackageId));if(!wpSnap.exists())throw new Error("Work package not found.");
 const wp=wpSnap.data(),ref=doc(collection(store,"tenderAwards")),record={id:ref.id,tenderId:rec.tenderId,tenderNumber:rec.tenderNumber,workPackageId:rec.workPackageId,workPackageCode:wp.packageCode||"",workPackageTitle:wp.packageTitle||"",dietId:rec.dietId,dietName:rec.dietName,executingAgencyId:rec.executingAgencyId,executingAgencyName:rec.executingAgencyName,contractorId:rec.contractorId,contractorCode:rec.contractorCode,contractorName:rec.contractorName,selectedTenderBidId:rec.recommendedTenderBidId,selectedFinancialBidId:rec.recommendedFinancialBidId,recommendationId:rec.id,financialRank:rec.financialRank,isL1:rec.isL1,tenderEstimatedValue:rec.tenderEstimatedValue,quotedAmount:rec.quotedAmount,evaluatedAmount:rec.evaluatedAmount,acceptedTenderAmount:rec.proposedAwardAmount,finalContractValue:input.finalContractValue,amountDifferenceFromTenderEstimate:variance.difference,percentDifferenceFromTenderEstimate:variance.percentDifference,tenderSavingAmount:variance.tenderSavingAmount,tenderSavingPercent:variance.tenderSavingPercent,excessOverTenderEstimateAmount:variance.excessAmount,excessOverTenderEstimatePercent:variance.excessPercent,contractCentralShare:input.finalContractValue*.6,contractStateShare:input.finalContractValue*.4,awardNumber:input.awardNumber.trim(),awardDate:input.awardDate,status:"approved",approvedBy:uid,approvedAt:serverTimestamp(),createdBy:uid,createdAt:serverTimestamp(),updatedBy:uid,updatedAt:serverTimestamp(),remarks:input.remarks?.trim()||""};
 const batch=writeBatch(store);batch.set(ref,record);batch.update(doc(store,"tenders",rec.tenderId),{awardStatus:"awarded",selectedContractorId:rec.contractorId,selectedContractorName:rec.contractorName,tenderAwardId:ref.id,updatedBy:uid,updatedAt:serverTimestamp()});batch.update(doc(store,"workPackages",rec.workPackageId),{status:"awarded",contractorId:rec.contractorId,contractorName:rec.contractorName,tenderAwardId:ref.id,finalContractValue:input.finalContractValue,updatedBy:uid,updatedAt:serverTimestamp()});audit(batch,"tender_award",ref.id,"tender_award_approved",uid,null,record,input.remarks);audit(batch,"workPackage",rec.workPackageId,"contractor_linked_to_work_package",uid,{contractorId:wp.contractorId||null},{contractorId:rec.contractorId,tenderAwardId:ref.id},input.remarks);await batch.commit();return ref.id;
}
export async function cancelTenderAward(id:string,reason:string){if(!reason.trim())throw new Error("Cancellation reason is required.");const{firestore,uid}=context(),user=await profile(),award=await getTenderAwardById(id);if(role(user)!=="scert_admin"||!award)throw new Error("SCERT Admin permission is required.");const next={status:"cancelled",cancelledBy:uid,cancelledAt:serverTimestamp(),cancellationReason:reason.trim(),updatedBy:uid,updatedAt:serverTimestamp()},batch=writeBatch(firestore);batch.update(doc(firestore,"tenderAwards",id),next);audit(batch,"tender_award",id,"tender_award_cancelled",uid,{status:award.status},next,reason);await batch.commit();}
