import { collection, doc, getDoc, getDocs, query, serverTimestamp, Timestamp, where, writeBatch } from "firebase/firestore";
import { auth, db, getFirebaseConfigurationMessage } from "../lib/firebase";
import type { AppUser, ProcurementMethod, Tender, TenderStatus, TenderType, WorkPackage } from "../types";
import { getPackageFinancialBasis } from "../utils/fundingCalculations";
import { canTransitionTenderStatus } from "../utils/tenderPermissions";

export type TenderInput = {
  workPackage: WorkPackage; tenderTitle: string; tenderNumber?: string; nitNumber?: string;
  tenderType: TenderType; procurementMethod: ProcurementMethod; estimatedTenderValue: number;
  valueVariationRemarks?: string; emdAmount?: number; tenderFee?: number; bidValidityDays?: number;
  noticeDate?: string; publicationDate?: string; documentDownloadStartDate?: string; bidSubmissionStartDate?: string;
  bidSubmissionEndDate?: string; preBidMeetingDate?: string; technicalBidOpeningDate?: string; financialBidOpeningDate?: string;
  completionPeriodValue?: number; completionPeriodUnit?: "days" | "months"; tenderPortalName?: string;
  tenderPortalReference?: string; tenderPortalUrl?: string; publicationRemarks?: string; internalRemarks?: string;
};

function context() { if (!db) throw new Error(getFirebaseConfigurationMessage()); if (!auth?.currentUser) throw new Error("You must be signed in."); return { firestore: db, uid: auth.currentUser.uid }; }
const mapTender = (snap: { id: string; data(): unknown }) => ({ id: snap.id, ...(snap.data() as object) }) as Tender;
const dateValue = (value?: string) => value ? Timestamp.fromDate(new Date(`${value}T00:00:00`)) : null;
const numberValue = (value?: number) => Number.isFinite(value) ? Number(value) : 0;

async function profile(): Promise<AppUser> { const { firestore, uid } = context(); const snap = await getDoc(doc(firestore, "users", uid)); if (!snap.exists()) throw new Error("User profile not found."); return { uid, ...snap.data() } as AppUser; }
function userRole(user: AppUser) { return user.systemRole || user.role; }
function assignedAgency(user: AppUser, agencyId: string) { return userRole(user) === "agency_user" && user.approvalStatus === "approved" && user.active === true && user.assignmentStatus === "assigned" && (user.assignedAgencyIds || []).includes(agencyId); }
function validateNonNegative(input: TenderInput) { for (const [label, value] of [["Estimated tender value", input.estimatedTenderValue], ["EMD amount", input.emdAmount], ["Tender fee", input.tenderFee], ["Bid validity days", input.bidValidityDays], ["Completion period", input.completionPeriodValue]] as const) if (value !== undefined && (!Number.isFinite(value) || value < 0)) throw new Error(`${label} cannot be negative.`); }
function validateDates(input: TenderInput) {
  const d = (value?: string) => value ? new Date(`${value}T00:00:00`).getTime() : null;
  const publication=d(input.publicationDate), start=d(input.bidSubmissionStartDate), end=d(input.bidSubmissionEndDate), preBid=d(input.preBidMeetingDate), technical=d(input.technicalBidOpeningDate);
  if (start !== null && end !== null && start > end) throw new Error("Bid Submission Start Date must be on or before Bid Submission End Date.");
  if (publication !== null && end !== null && publication > end) throw new Error("Publication Date must be on or before Bid Submission End Date.");
  if (technical !== null && end !== null && technical < end) throw new Error("Technical Bid Opening Date must be on or after Bid Submission End Date.");
  if (preBid !== null && end !== null && preBid > end) throw new Error("Pre-Bid Meeting Date must be on or before Bid Submission End Date.");
}
function validate(input: TenderInput, submitting=false) {
  validateNonNegative(input); validateDates(input);
  const basis=getPackageFinancialBasis(input.workPackage), variation=Number(input.estimatedTenderValue)-basis;
  if (variation !== 0 && !input.valueVariationRemarks?.trim()) throw new Error("Value Variation Remarks are required when the tender value differs from the work-package financial basis.");
  if (submitting && (!input.tenderTitle.trim() || (!input.tenderNumber?.trim() && !input.nitNumber?.trim()) || !input.tenderType || !input.procurementMethod || !input.bidSubmissionEndDate || !input.technicalBidOpeningDate || !input.completionPeriodValue || input.completionPeriodValue <= 0)) throw new Error("Complete the required tender information, closing/opening dates, and completion period before submission.");
}
function data(input: TenderInput) {
  const wp=input.workPackage, sourceFinancialBasis=getPackageFinancialBasis(wp), estimatedTenderValue=Number(input.estimatedTenderValue), valueVariationAmount=estimatedTenderValue-sourceFinancialBasis;
  return { tenderTitle: input.tenderTitle.trim(), tenderNumber: input.tenderNumber?.trim()||"", nitNumber: input.nitNumber?.trim()||"", workPackageId:wp.id, workPackageCode:wp.packageCode, workPackageTitle:wp.packageTitle, scopeOfWorkId:wp.scopeOfWorkId||"", dietId:wp.dietId, dietName:wp.dietName, districtId:wp.districtId||"", districtName:wp.districtName||"", phaseId:wp.phaseId||"", phaseName:wp.phaseName||"", dietAgencyAssignmentId:wp.dietAgencyAssignmentId, executingAgencyId:wp.executingAgencyId, executingAgencyName:wp.executingAgencyName, executingAgencyType:wp.executingAgencyType||"", tenderType:input.tenderType, procurementMethod:input.procurementMethod, sourceFinancialBasis, estimatedTenderValue, valueVariationAmount, valueVariationPercent:sourceFinancialBasis ? valueVariationAmount/sourceFinancialBasis*100 : 0, valueVariationRemarks:input.valueVariationRemarks?.trim()||"", emdAmount:numberValue(input.emdAmount), tenderFee:numberValue(input.tenderFee), bidValidityDays:numberValue(input.bidValidityDays), noticeDate:dateValue(input.noticeDate), publicationDate:dateValue(input.publicationDate), documentDownloadStartDate:dateValue(input.documentDownloadStartDate), bidSubmissionStartDate:dateValue(input.bidSubmissionStartDate), bidSubmissionEndDate:dateValue(input.bidSubmissionEndDate), preBidMeetingDate:dateValue(input.preBidMeetingDate), technicalBidOpeningDate:dateValue(input.technicalBidOpeningDate), financialBidOpeningDate:dateValue(input.financialBidOpeningDate), completionPeriodValue:numberValue(input.completionPeriodValue), completionPeriodUnit:input.completionPeriodUnit||"months", tenderPortalName:input.tenderPortalName?.trim()||"", tenderPortalReference:input.tenderPortalReference?.trim()||"", tenderPortalUrl:input.tenderPortalUrl?.trim()||"", publicationRemarks:input.publicationRemarks?.trim()||"", internalRemarks:input.internalRemarks?.trim()||"" };
}
function audit(batch: ReturnType<typeof writeBatch>, firestore: NonNullable<typeof db>, id:string, action:string, uid:string, previous:unknown, next:unknown, remarks="") { batch.set(doc(collection(firestore,"auditLogs")),{entityType:"tender",entityId:id,action,performedBy:uid,performedAt:serverTimestamp(),previousData:previous,newData:next,remarks}); }

export async function getTenders(){const{firestore}=context();return(await getDocs(collection(firestore,"tenders"))).docs.map(mapTender);}
export async function getTenderById(id:string){const{firestore}=context();const snap=await getDoc(doc(firestore,"tenders",id));return snap.exists()?mapTender(snap):null;}
async function getBy(field:string,value:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"tenders"),where(field,"==",value)))).docs.map(mapTender);}
export const getTendersForDiet=(id:string)=>getBy("dietId",id); export const getTendersForAgency=(id:string)=>getBy("executingAgencyId",id); export const getTendersForWorkPackage=(id:string)=>getBy("workPackageId",id);
export async function checkExistingTenderForWorkPackage(id:string){return(await getTendersForWorkPackage(id)).find(t=>t.status!=="cancelled"&&t.status!=="retender_required")||null;}

async function assertSource(wp:WorkPackage,user:AppUser){if(wp.status!=="approved_for_tender")throw new Error("Tender creation requires an approved-for-tender work package.");if(userRole(user)!=="scert_admin"&&!assignedAgency(user,wp.executingAgencyId))throw new Error("You do not have permission to create a tender for this package.");const{firestore}=context();const assignment=await getDoc(doc(firestore,"dietAgencyAssignments",wp.dietAgencyAssignmentId));if(!assignment.exists()||assignment.data().status!=="active"||assignment.data().dietId!==wp.dietId||assignment.data().executingAgencyId!==wp.executingAgencyId)throw new Error("The executing-agency assignment for this package is no longer active. SCERT review is required.");}
async function assertTenderSource(tender:Tender){const{firestore}=context(),wp=await getDoc(doc(firestore,"workPackages",tender.workPackageId));if(!wp.exists())throw new Error("The source Work Package no longer exists.");const packageData=wp.data();if(!["approved_for_tender","tender_in_progress"].includes(packageData.status)||packageData.dietId!==tender.dietId||packageData.executingAgencyId!==tender.executingAgencyId)throw new Error("The source Work Package is not valid for this tender workflow.");const assignment=await getDoc(doc(firestore,"dietAgencyAssignments",tender.dietAgencyAssignmentId));if(!assignment.exists()||assignment.data().status!=="active"||assignment.data().dietId!==tender.dietId||assignment.data().executingAgencyId!==tender.executingAgencyId)throw new Error("The executing-agency assignment is no longer valid.");}
export async function createTender(input:TenderInput){validate(input);const{firestore,uid}=context(),user=await profile();await assertSource(input.workPackage,user);if(await checkExistingTenderForWorkPackage(input.workPackage.id))throw new Error("An active tender already exists for this work package.");const ref=doc(collection(firestore,"tenders")),record={id:ref.id,...data(input),status:"draft" as TenderStatus,createdBy:uid,createdAt:serverTimestamp(),updatedBy:uid,updatedAt:serverTimestamp()};const batch=writeBatch(firestore);batch.set(ref,record);audit(batch,firestore,ref.id,"tender_created",uid,null,record,input.internalRemarks);await batch.commit();return ref.id;}
export async function updateTender(id:string,input:TenderInput){validate(input);const{firestore,uid}=context(),user=await profile(),ref=doc(firestore,"tenders",id),snap=await getDoc(ref);if(!snap.exists())throw new Error("Tender not found.");const old=mapTender(snap);if(userRole(user)!=="scert_admin"&&!(assignedAgency(user,old.executingAgencyId)&&["draft","revision_required"].includes(old.status)))throw new Error("This tender cannot be edited in its current status.");const next={...data({...input,workPackage:{...input.workPackage,id:old.workPackageId,dietId:old.dietId,executingAgencyId:old.executingAgencyId,dietAgencyAssignmentId:old.dietAgencyAssignmentId}}),updatedBy:uid,updatedAt:serverTimestamp()};const batch=writeBatch(firestore);batch.update(ref,next);audit(batch,firestore,id,userRole(user)==="scert_admin"?"scert_tender_edit":"tender_updated",uid,snap.data(),next,input.internalRemarks);await batch.commit();}
async function transition(id:string,allowed:TenderStatus[],status:TenderStatus,action:string,remarks=""){const{firestore,uid}=context(),user=await profile(),ref=doc(firestore,"tenders",id),snap=await getDoc(ref);if(!snap.exists()||!allowed.includes(snap.data().status))throw new Error("Tender is not in the required status for this action.");const tender=mapTender(snap),role=userRole(user),admin=role==="scert_admin",agency=assignedAgency(user,tender.executingAgencyId);if(!canTransitionTenderStatus(tender.status,status,role)&&!["cancelled","retender_required"].includes(status))throw new Error("This tender status transition is not permitted.");if(["approved_for_publication","revision_required","cancelled","retender_required"].includes(status)&&!admin)throw new Error("SCERT Admin permission is required.");if(status==="submitted_for_review"&&!agency&&!admin)throw new Error("You do not have permission to submit this tender.");if(status==="published"&&!admin&&!agency)throw new Error("You do not have permission to publish this tender.");const next:Record<string,unknown>={status,updatedBy:uid,updatedAt:serverTimestamp()};if(status==="submitted_for_review")Object.assign(next,{submittedBy:uid,submittedAt:serverTimestamp()});if(status==="revision_required")Object.assign(next,{revisionRemarks:remarks,revisionRequestedBy:uid,revisionRequestedAt:serverTimestamp(),reviewedBy:uid,reviewedAt:serverTimestamp()});if(status==="approved_for_publication")Object.assign(next,{approvedForPublicationBy:uid,approvedForPublicationAt:serverTimestamp(),scertReviewRemarks:remarks,reviewedBy:uid,reviewedAt:serverTimestamp()});if(status==="published")Object.assign(next,{publishedBy:uid,publishedAt:serverTimestamp()});if(status==="cancelled")Object.assign(next,{cancelledBy:uid,cancelledAt:serverTimestamp(),cancellationReason:remarks});const batch=writeBatch(firestore);batch.update(ref,next);if(status==="published"){batch.update(doc(firestore,"workPackages",tender.workPackageId),{status:"tender_in_progress",updatedBy:uid,updatedAt:serverTimestamp()});batch.set(doc(collection(firestore,"auditLogs")),{entityType:"workPackage",entityId:tender.workPackageId,action:"tender_published",performedBy:uid,performedAt:serverTimestamp(),previousData:{status:"approved_for_tender"},newData:{status:"tender_in_progress"},remarks:`Tender ${tender.tenderNumber||tender.nitNumber} published.`});}audit(batch,firestore,id,action,uid,snap.data(),next,remarks);await batch.commit();}
export async function submitTenderForReview(id:string){const tender=await getTenderById(id);if(!tender)throw new Error("Tender not found.");await assertTenderSource(tender);validate({workPackage:{status:"approved_for_tender",estimatedCost:tender.sourceFinancialBasis,administrativeApprovalAmount:0,technicalSanctionAmount:0} as WorkPackage,tenderTitle:tender.tenderTitle,tenderNumber:tender.tenderNumber,nitNumber:tender.nitNumber,tenderType:tender.tenderType,procurementMethod:tender.procurementMethod,estimatedTenderValue:tender.estimatedTenderValue,valueVariationRemarks:tender.valueVariationRemarks,bidSubmissionEndDate:toInputDate(tender.bidSubmissionEndDate),technicalBidOpeningDate:toInputDate(tender.technicalBidOpeningDate),completionPeriodValue:tender.completionPeriodValue},true);await transition(id,["draft","revision_required"],"submitted_for_review",tender.status==="revision_required"?"resubmit_to_scert":"submit_to_scert");}
export const returnTenderForRevision=(id:string,remarks:string)=>{if(!remarks.trim())throw new Error("Revision Remarks are required.");return transition(id,["submitted_for_review"],"revision_required","tender_returned_for_revision",remarks.trim());};
export async function approveTenderForPublication(id:string,remarks=""){const tender=await getTenderById(id);if(!tender)throw new Error("Tender not found.");await assertTenderSource(tender);validate({workPackage:{status:"approved_for_tender",estimatedCost:tender.sourceFinancialBasis,administrativeApprovalAmount:0,technicalSanctionAmount:0} as WorkPackage,tenderTitle:tender.tenderTitle,tenderNumber:tender.tenderNumber,nitNumber:tender.nitNumber,tenderType:tender.tenderType,procurementMethod:tender.procurementMethod,estimatedTenderValue:tender.estimatedTenderValue,valueVariationRemarks:tender.valueVariationRemarks,bidSubmissionEndDate:toInputDate(tender.bidSubmissionEndDate),technicalBidOpeningDate:toInputDate(tender.technicalBidOpeningDate),completionPeriodValue:tender.completionPeriodValue},true);return transition(id,["submitted_for_review"],"approved_for_publication","approve_for_publication",remarks.trim());}
export async function publishTender(id:string){const tender=await getTenderById(id);if(!tender||(!tender.tenderNumber&&!tender.nitNumber)||!tender.publicationDate||!tender.bidSubmissionEndDate||!tender.technicalBidOpeningDate||tender.estimatedTenderValue<0)throw new Error("Tender/NIT Number, Publication Date, closing/opening dates, and estimated value are required before publication.");await assertTenderSource(tender);await transition(id,["approved_for_publication"],"published","publish");}
export const cancelTender=(id:string,reason:string)=>{if(!reason.trim())throw new Error("Cancellation reason is required.");return transition(id,["draft","submitted_for_review","revision_required","approved_for_publication","published"],"cancelled","tender_cancelled",reason.trim());};
export const markTenderForRetender=(id:string,remarks:string)=>transition(id,["cancelled"],"retender_required","tender_retender_required",remarks.trim());
export function toInputDate(value:unknown){if(!value)return"";const date=value&&typeof value==="object"&&"toDate" in value?(value as{toDate():Date}).toDate():new Date(String(value));return Number.isNaN(date.getTime())?"":date.toISOString().slice(0,10);}
