import { collection, doc, getDoc, getDocs, query, serverTimestamp, where, writeBatch } from "firebase/firestore";
import { auth, db } from "../lib/firebase";
import type { AppUser, TenderAward, WorkOrder } from "../types";
import { calculateScheduledCompletionDate } from "../utils/tenderAward";
import { getTenderAwardById } from "./tenderAwardService";
function context(){if(!db||!auth?.currentUser)throw new Error("Firebase is not configured or the user is not signed in.");return{firestore:db,uid:auth.currentUser.uid};}
async function profile(){const{firestore,uid}=context(),s=await getDoc(doc(firestore,"users",uid));if(!s.exists())throw new Error("User profile not found.");return{uid,...s.data()} as AppUser;}
const role=(p:AppUser)=>p.systemRole||p.role,assigned=(p:AppUser,id:string)=>role(p)==="scert_admin"||p.primaryAgencyId===id||Boolean(p.assignedAgencyIds?.includes(id));
const map=(s:{id:string;data():unknown})=>({id:s.id,...(s.data() as Record<string,unknown>)} as WorkOrder);
function audit(batch:ReturnType<typeof writeBatch>,id:string,action:string,uid:string,previous:unknown,next:unknown,remarks=""){const{firestore}=context();batch.set(doc(collection(firestore,"auditLogs")),{entityType:"work_order",entityId:id,action,performedBy:uid,performedAt:serverTimestamp(),previousData:previous,newData:next,remarks});}
export async function getWorkOrders(){const{firestore}=context();return(await getDocs(collection(firestore,"workOrders"))).docs.map(map);}
export async function getWorkOrdersForAgency(executingAgencyId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"workOrders"),where("executingAgencyId","==",executingAgencyId)))).docs.map(map);}
export async function getWorkOrdersForDiet(dietId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"workOrders"),where("dietId","==",dietId)))).docs.map(map);}
export async function getWorkOrdersForAward(tenderAwardId:string){const{firestore}=context();return(await getDocs(query(collection(firestore,"workOrders"),where("tenderAwardId","==",tenderAwardId)))).docs.map(map);}
export async function getWorkOrderById(id:string){const{firestore}=context(),s=await getDoc(doc(firestore,"workOrders",id));return s.exists()?map(s):null;}
export type WorkOrderInput={workOrderNumber:string;workOrderDate:string;commencementDate?:string;completionPeriodValue:number;completionPeriodUnit:"days"|"months";performanceSecurityAmount?:number;performanceSecurityPercent?:number;securityDepositPercent?:number;retentionPercent?:number;agreementNumber?:string;agreementDate?:string;remarks?:string;};
function validate(input:WorkOrderInput){if(!input.workOrderNumber.trim()||!input.workOrderDate)throw new Error("Work Order Number and Work Order Date are required.");if(!Number.isFinite(input.completionPeriodValue)||input.completionPeriodValue<=0)throw new Error("Completion period must be greater than zero.");for(const x of [input.performanceSecurityAmount,input.performanceSecurityPercent,input.securityDepositPercent,input.retentionPercent])if(x!==undefined&&(!Number.isFinite(x)||x<0))throw new Error("Security values must be zero or greater.");}
export async function createWorkOrder(tenderAwardId:string,input:WorkOrderInput,existingId?:string){validate(input);const{firestore,uid}=context(),user=await profile(),award=await getTenderAwardById(tenderAwardId);if(!award||!["approved","awarded","award_letter_issued","work_order_pending"].includes(award.status))throw new Error("Work order requires a valid tender award.");if(!assigned(user,award.executingAgencyId))throw new Error("You are not authorised for this executing agency.");const old=existingId?await getWorkOrderById(existingId):null;if(old&&old.status!=="draft"&&role(user)!=="scert_admin")throw new Error("Issued work orders are locked.");if(!old&&(await getWorkOrdersForAward(tenderAwardId)).some(x=>x.status!=="cancelled"))throw new Error("An active work order already exists for this award.");const ref=old?doc(firestore,"workOrders",old.id):doc(collection(firestore,"workOrders")),scheduled=calculateScheduledCompletionDate(input.commencementDate,input.completionPeriodValue,input.completionPeriodUnit);const record={id:ref.id,workOrderNumber:input.workOrderNumber.trim(),workOrderDate:input.workOrderDate,tenderAwardId:award.id,tenderId:award.tenderId,workPackageId:award.workPackageId,dietId:award.dietId,dietName:award.dietName,executingAgencyId:award.executingAgencyId,executingAgencyName:award.executingAgencyName,contractorId:award.contractorId,contractorCode:award.contractorCode,contractorName:award.contractorName,contractValue:award.finalContractValue,commencementDate:input.commencementDate||null,completionPeriodValue:input.completionPeriodValue,completionPeriodUnit:input.completionPeriodUnit,scheduledCompletionDate:scheduled,performanceSecurityAmount:input.performanceSecurityAmount??0,performanceSecurityPercent:input.performanceSecurityPercent??0,securityDepositPercent:input.securityDepositPercent??0,retentionPercent:input.retentionPercent??0,agreementNumber:input.agreementNumber?.trim()||"",agreementDate:input.agreementDate||null,status:"draft",issuedBy:old?.issuedBy||"",issuedAt:old?.issuedAt||null,createdBy:old?.createdBy||uid,createdAt:old?.createdAt||serverTimestamp(),updatedBy:uid,updatedAt:serverTimestamp(),remarks:input.remarks?.trim()||""};const batch=writeBatch(firestore);old?batch.update(ref,record):batch.set(ref,record);batch.update(doc(firestore,"tenderAwards",award.id),{status:"work_order_pending",updatedBy:uid,updatedAt:serverTimestamp()});audit(batch,ref.id,old?"work_order_updated":"work_order_created",uid,old,record,input.remarks);await batch.commit();return ref.id;}
export async function issueWorkOrder(id:string){const{firestore,uid}=context(),user=await profile(),order=await getWorkOrderById(id);if(!order||order.status!=="draft"||!assigned(user,order.executingAgencyId))throw new Error("This work order cannot be issued.");const award=await getTenderAwardById(order.tenderAwardId);if(!award||!["approved","awarded","award_letter_issued","work_order_pending"].includes(award.status))throw new Error("Tender award is not valid for issuance.");const next={status:"issued",issuedBy:uid,issuedAt:serverTimestamp(),updatedBy:uid,updatedAt:serverTimestamp()},batch=writeBatch(firestore);batch.update(doc(firestore,"workOrders",id),next);batch.update(doc(firestore,"tenderAwards",order.tenderAwardId),{status:"work_order_issued",updatedBy:uid,updatedAt:serverTimestamp()});batch.update(doc(firestore,"workPackages",order.workPackageId),{workOrderId:id,workOrderNumber:order.workOrderNumber,workOrderStatus:"issued",updatedBy:uid,updatedAt:serverTimestamp()});audit(batch,id,"work_order_issued",uid,{status:order.status},next);await batch.commit();}
export async function cancelWorkOrder(id:string,reason:string){if(!reason.trim())throw new Error("Cancellation reason is required.");const{firestore,uid}=context(),user=await profile(),order=await getWorkOrderById(id);if(role(user)!=="scert_admin"||!order)throw new Error("SCERT Admin permission is required.");const next={status:"cancelled",cancelledBy:uid,cancelledAt:serverTimestamp(),cancellationReason:reason.trim(),updatedBy:uid,updatedAt:serverTimestamp()},batch=writeBatch(firestore);batch.update(doc(firestore,"workOrders",id),next);audit(batch,id,"work_order_cancelled",uid,{status:order.status},next,reason);await batch.commit();}
