import { onRequest } from "firebase-functions/v2/https";
import { initializeApp } from "firebase-admin/app";
import { getAuth } from "firebase-admin/auth";
import { FieldValue, getFirestore } from "firebase-admin/firestore";

initializeApp();
const db=getFirestore(),adminAuth=getAuth();
const deletedCollections=["workOrders","tenderAwards","tenderAwardRecommendations","tenderFinancialBids","tenderTechnicalCriteria","tenderBids","tenderCorrigenda","tenders","workPackageActivities","workPackages","packageCounters","financialTransactions","scopeOfWorks","drawingPackages","communications","documentAttachments","userAssignments","dietAgencyAssignments","registrationRequests","contractors","notifications","auditLogs"] as const;
const preservedCollections=["diets","activities","activityMaster","phases","systemConfig","districts","roles","agencies","systemAuditLogs"] as const;
const allowedOrigins=(process.env.ADMIN_UI_ORIGINS||"").split(",").map(x=>x.trim()).filter(Boolean);

function cors(req:any,res:any){const origin=String(req.headers.origin||"");if(origin&&allowedOrigins.includes(origin))res.set("Access-Control-Allow-Origin",origin);res.set("Vary","Origin");res.set("Access-Control-Allow-Headers","Authorization, Content-Type");res.set("Access-Control-Allow-Methods","GET, POST, OPTIONS");}
function configuredProtectedUids(){return new Set((process.env.PROTECTED_SCERT_UIDS||"").split(",").map(x=>x.trim()).filter(Boolean));}
async function caller(req:any){const token=String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");if(!token)throw new Error("Authentication required.");const decoded=await adminAuth.verifyIdToken(token,true),profile=await db.collection("users").doc(decoded.uid).get();if(!profile.exists||profile.data()?.active===false||(profile.data()?.systemRole||profile.data()?.role)!=="scert_admin")throw new Error("SCERT Admin permission is required.");const protectedUids=configuredProtectedUids();if(protectedUids.size&&!protectedUids.has(decoded.uid))throw new Error("This SCERT Admin is not authorised for database reset.");return decoded.uid;}
async function collectionCount(name:string){return(await db.collection(name).count().get()).data().count;}
async function profiles(){return db.collection("users").get();}
async function phaseSequences(){const snap=await db.collection("phases").get(),map=new Map<string,number>();snap.docs.forEach(item=>map.set(item.id,Number(item.data().phaseSequence||item.data().order||0)));return map;}
function sequenceOf(data:FirebaseFirestore.DocumentData,phases:Map<string,number>){return Number(data.phaseSequence||phases.get(String(data.phaseId||""))||0);}
async function financialBaselineCounts(){const phases=await phaseSequences(),snap=await db.collection("dietActivityFinancials").get();let preserved=0,reset=0;for(const item of snap.docs)(sequenceOf(item.data(),phases)>0&&sequenceOf(item.data(),phases)<=2?preserved++:reset++);return{preserved,reset};}

async function preview(){
 const users=await profiles(),nonAdmins=users.docs.filter(x=>(x.data().systemRole||x.data().role)!=="scert_admin"),admins=users.size-nonAdmins.length,architectureUsers=nonAdmins.filter(x=>(x.data().systemRole||x.data().role)==="architecture_user").length;
 const deleted:Record<string,number>={};for(const name of deletedCollections)deleted[name]=await collectionCount(name);deleted.users=nonAdmins.length;deleted.architectureUsers=architectureUsers;
 const registrations=await db.collection("registrationRequests").get();deleted.architectureRegistrations=registrations.docs.filter(x=>x.data().organisationRole==="architecture_department"||x.data().requestedSystemRole==="architecture_user").length;
 const assignments=await db.collection("userAssignments").get();deleted.architectureAssignments=assignments.docs.filter(x=>x.data().organisationRole==="architecture_department"||x.data().systemRole==="architecture_user").length;
 const financials=await financialBaselineCounts();deleted.phase3PlusActivityFinancials=financials.reset;
 const preserved:Record<string,number>={scertAdmins:admins,phase1And2ActivityFinancials:financials.preserved};for(const name of preservedCollections)preserved[name]=await collectionCount(name);return{deleted,preserved};
}

async function deleteCollection(name:string){let total=0;for(;;){const snap=await db.collection(name).limit(400).get();if(snap.empty)return total;const batch=db.batch();snap.docs.forEach(x=>batch.delete(x.ref));await batch.commit();total+=snap.size;}}
async function resetActivityFinancials(){
 const phases=await phaseSequences(),snap=await db.collection("dietActivityFinancials").get();let preserved=0,deleted=0;
 for(let i=0;i<snap.docs.length;i+=400){const batch=db.batch();for(const item of snap.docs.slice(i,i+400)){const sequence=sequenceOf(item.data(),phases);if(sequence>0&&sequence<=2){batch.update(item.ref,{phaseSequence:sequence,committedToWorkPackages:FieldValue.delete(),availableForNewWorkPackages:FieldValue.delete(),releasedAmount:FieldValue.delete(),transferredAmount:FieldValue.delete(),expenditure:FieldValue.delete(),utilisedAmount:FieldValue.delete(),workPackageCount:FieldValue.delete(),progress:FieldValue.delete(),updatedAt:FieldValue.serverTimestamp()});preserved++;}else{batch.delete(item.ref);deleted++;}}await batch.commit();}return{preserved,deleted};
}
async function deleteNonAdminUsers(){
 const snap=await profiles(),protectedUids=configuredProtectedUids();for(const item of snap.docs)if((item.data().systemRole||item.data().role)==="scert_admin"&&item.data().active!==false)protectedUids.add(item.id);
 let deletedProfiles=0,deletedAuth=0,deletedArchitectureUsers=0,deletedOtherUsers=0;
 for(const item of snap.docs){if(protectedUids.has(item.id))continue;const architecture=(item.data().systemRole||item.data().role)==="architecture_user"||item.data().organisationRole==="architecture_department";await item.ref.delete();deletedProfiles++;architecture?deletedArchitectureUsers++:deletedOtherUsers++;try{await adminAuth.deleteUser(item.id);deletedAuth++;}catch(e:any){if(e?.code!=="auth/user-not-found")throw e;}}
 let pageToken:string|undefined;do{const page=await adminAuth.listUsers(500,pageToken);for(const user of page.users)if(!protectedUids.has(user.uid)){await adminAuth.deleteUser(user.uid);deletedAuth++;}pageToken=page.pageToken;}while(pageToken);
 return{deletedProfiles,deletedAuth,deletedArchitectureUsers,deletedOtherUsers,preservedScertAdmins:protectedUids.size,protectedUids};
}
async function resetDiets(){const snap=await db.collection("diets").get();for(let i=0;i<snap.docs.length;i+=400){const batch=db.batch();for(const item of snap.docs.slice(i,i+400))batch.update(item.ref,{assignedAgencyId:FieldValue.delete(),nodalOfficerUid:FieldValue.delete(),activeWorkPackageCount:FieldValue.delete(),tenderCount:FieldValue.delete(),physicalProgress:FieldValue.delete(),physicalProgressPercent:FieldValue.delete(),financialProgress:FieldValue.delete(),financialProgressPercent:FieldValue.delete(),fundsReleased:0,expenditure:0,updatedAt:FieldValue.serverTimestamp()});await batch.commit();}return snap.size;}
async function verifyReset(protectedUids:Set<string>,expectedFinancialBaselineCount:number){const errors:string[]=[];for(const name of deletedCollections)if(await collectionCount(name)!==0)errors.push(`${name} still contains records.`);const financials=await financialBaselineCounts();if(financials.reset!==0)errors.push("Phase III+ activity financial records remain.");if(financials.preserved!==expectedFinancialBaselineCount)errors.push(`Phase I/II financial baseline count changed from ${expectedFinancialBaselineCount} to ${financials.preserved}.`);for(const uid of protectedUids)if(!(await db.collection("users").doc(uid).get()).exists)errors.push(`Protected SCERT Admin ${uid} is missing.`);const users=await profiles();if(users.docs.some(x=>(x.data().systemRole||x.data().role)==="architecture_user"||x.data().organisationRole==="architecture_department"))errors.push("An operational Architecture user remains.");return{errors,preservedFinancialBaselineCount:financials.preserved};}

export const databaseReset=onRequest({cors:false,timeoutSeconds:540,memory:"1GiB"},async(req,res)=>{cors(req,res);if(req.method==="OPTIONS"){res.status(204).send("");return;}try{const uid=await caller(req),enabled=process.env.ALLOW_DATABASE_RESET==="true";if(req.method==="GET"){res.json({enabled,...await preview()});return;}if(req.method!=="POST"){res.status(405).json({error:"Method not allowed."});return;}if(!enabled){res.status(403).json({error:"Database reset is disabled in this environment."});return;}if(req.body?.confirmation!=="RESET DATABASE"){res.status(400).json({error:"Exact typed confirmation is required."});return;}
 const expectedFinancialBaselineCount=(await financialBaselineCounts()).preserved,deleted:Record<string,number>={},errors:string[]=[];for(const name of deletedCollections){try{deleted[name]=await deleteCollection(name);}catch{errors.push(`Unable to completely reset ${name}.`);}}
 let financialResult={preserved:0,deleted:0};try{financialResult=await resetActivityFinancials();deleted.phase3PlusActivityFinancials=financialResult.deleted;}catch{errors.push("Unable to preserve the Phase I/II financial baseline cleanly.");}
 let userResult={deletedProfiles:0,deletedAuth:0,deletedArchitectureUsers:0,deletedOtherUsers:0,preservedScertAdmins:0,protectedUids:new Set<string>()};try{userResult=await deleteNonAdminUsers();}catch{errors.push("Unable to completely reset non-SCERT users.");}
 let dietsPreserved=0;try{dietsPreserved=await resetDiets();}catch{errors.push("Unable to reset DIET operational fields.");}
 const verification=await verifyReset(userResult.protectedUids,expectedFinancialBaselineCount);errors.push(...verification.errors);
 const result={status:errors.length?"completed_with_errors":"completed",deleted:{...deleted,users:userResult.deletedProfiles,firebaseAuthUsers:userResult.deletedAuth,architectureUsers:userResult.deletedArchitectureUsers,otherOperationalUsers:userResult.deletedOtherUsers},preserved:{scertAdmins:userResult.preservedScertAdmins,diets:dietsPreserved,activities:await collectionCount("activities"),activityMaster:await collectionCount("activityMaster"),phases:await collectionCount("phases"),agencies:await collectionCount("agencies"),systemConfig:await collectionCount("systemConfig"),phase1And2ActivityFinancials:verification.preservedFinancialBaselineCount},errors};
 await db.collection("systemAuditLogs").add({action:"database_reset",performedBy:uid,performedAt:FieldValue.serverTimestamp(),deletedCounts:result.deleted,preservedCounts:result.preserved,preservedFinancialBaselineCount:verification.preservedFinancialBaselineCount,deletedArchitectureUsers:userResult.deletedArchitectureUsers,deletedOtherUsers:userResult.deletedOtherUsers,status:result.status,errors});res.status(errors.length?207:200).json(result);
 }catch(e){res.status(403).json({error:e instanceof Error?e.message:"Database reset failed."});}});
