import { onRequest } from "firebase-functions/v2/https";
import { initializeApp } from "firebase-admin/app";
import { getAuth } from "firebase-admin/auth";
import { FieldValue, getFirestore } from "firebase-admin/firestore";

initializeApp();
const db=getFirestore(),adminAuth=getAuth();
const deletedCollections=["workOrders","tenderAwards","tenderAwardRecommendations","tenderFinancialBids","dietActivityFinancials","tenderTechnicalCriteria","tenderBids","tenderCorrigenda","tenders","workPackageActivities","workPackages","scopeOfWorks","userAssignments","dietAgencyAssignments","registrationRequests","contractors","notifications","auditLogs"] as const;
const preservedCollections=["diets","activities","activityMaster","phases","systemConfig","districts","roles","agencies","systemAuditLogs"] as const;
const allowedOrigins=(process.env.ADMIN_UI_ORIGINS||"").split(",").map(x=>x.trim()).filter(Boolean);

function cors(req:any,res:any){const origin=String(req.headers.origin||"");if(origin&&allowedOrigins.includes(origin))res.set("Access-Control-Allow-Origin",origin);res.set("Vary","Origin");res.set("Access-Control-Allow-Headers","Authorization, Content-Type");res.set("Access-Control-Allow-Methods","GET, POST, OPTIONS");}
async function caller(req:any){const token=String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");if(!token)throw new Error("Authentication required.");const decoded=await adminAuth.verifyIdToken(token,true),profile=await db.collection("users").doc(decoded.uid).get();if(!profile.exists||profile.data()?.active===false||(profile.data()?.systemRole||profile.data()?.role)!=="scert_admin")throw new Error("SCERT Admin permission is required.");const protectedUids=(process.env.PROTECTED_SCERT_UIDS||"").split(",").map(x=>x.trim()).filter(Boolean);if(protectedUids.length&&!protectedUids.includes(decoded.uid))throw new Error("This SCERT Admin is not authorised for database reset.");return decoded.uid;}
async function collectionCount(name:string){const snap=await db.collection(name).count().get();return snap.data().count;}
async function profiles(){return db.collection("users").get();}
async function preview(){const users=await profiles(),nonAdmins=users.docs.filter(x=>(x.data().systemRole||x.data().role)!=="scert_admin").length,admins=users.size-nonAdmins;const deleted:Record<string,number>={};for(const name of deletedCollections)deleted[name]=await collectionCount(name);deleted.users=nonAdmins;const preserved:Record<string,number>={scertAdmins:admins};for(const name of preservedCollections)preserved[name]=await collectionCount(name);return{deleted,preserved};}
async function deleteCollection(name:string){let total=0;for(;;){const snap=await db.collection(name).limit(400).get();if(snap.empty)return total;const batch=db.batch();snap.docs.forEach(x=>batch.delete(x.ref));await batch.commit();total+=snap.size;}}
async function deleteNonAdminUsers(){const snap=await profiles(),protectedUids=new Set<string>((process.env.PROTECTED_SCERT_UIDS||"").split(",").map(x=>x.trim()).filter(Boolean));for(const item of snap.docs){if((item.data().systemRole||item.data().role)==="scert_admin"&&item.data().active!==false)protectedUids.add(item.id);}let deletedProfiles=0,deletedAuth=0;for(const item of snap.docs){if(protectedUids.has(item.id))continue;await item.ref.delete();deletedProfiles++;try{await adminAuth.deleteUser(item.id);deletedAuth++;}catch(e:any){if(e?.code!=="auth/user-not-found")throw e;}}let pageToken:string|undefined;do{const page=await adminAuth.listUsers(500,pageToken);for(const user of page.users){if(!protectedUids.has(user.uid)){await adminAuth.deleteUser(user.uid);deletedAuth++;}}pageToken=page.pageToken;}while(pageToken);return{deletedProfiles,deletedAuth,preservedScertAdmins:protectedUids.size};}
async function resetDiets(){const snap=await db.collection("diets").get();for(let i=0;i<snap.docs.length;i+=400){const batch=db.batch();for(const item of snap.docs.slice(i,i+400))batch.update(item.ref,{assignedAgencyId:FieldValue.delete(),nodalOfficerUid:FieldValue.delete(),activeWorkPackageCount:FieldValue.delete(),tenderCount:FieldValue.delete(),physicalProgress:FieldValue.delete(),physicalProgressPercent:FieldValue.delete(),financialProgress:FieldValue.delete(),financialProgressPercent:FieldValue.delete(),updatedAt:FieldValue.serverTimestamp()});await batch.commit();}return snap.size;}

export const databaseReset=onRequest({cors:false,timeoutSeconds:540,memory:"1GiB"},async(req,res)=>{cors(req,res);if(req.method==="OPTIONS"){res.status(204).send("");return;}try{const uid=await caller(req),enabled=process.env.ALLOW_DATABASE_RESET==="true";if(req.method==="GET"){res.json({enabled,...await preview()});return;}if(req.method!=="POST"){res.status(405).json({error:"Method not allowed."});return;}if(!enabled){res.status(403).json({error:"Database reset is disabled in this environment."});return;}if(req.body?.confirmation!=="RESET DATABASE"){res.status(400).json({error:"Exact typed confirmation is required."});return;}const deleted:Record<string,number>={},errors:string[]=[];for(const name of deletedCollections){try{deleted[name]=await deleteCollection(name);}catch{errors.push(`Unable to completely reset ${name}.`);}}let userResult={deletedProfiles:0,deletedAuth:0,preservedScertAdmins:0};try{userResult=await deleteNonAdminUsers();}catch{errors.push("Unable to completely reset non-SCERT users.");}let dietsPreserved=0;try{dietsPreserved=await resetDiets();}catch{errors.push("Unable to reset DIET operational fields.");}const result={status:errors.length?"completed_with_errors":"completed",deleted:{...deleted,users:userResult.deletedProfiles,firebaseAuthUsers:userResult.deletedAuth},preserved:{scertAdmins:userResult.preservedScertAdmins,diets:dietsPreserved,activities:await collectionCount("activities"),phases:await collectionCount("phases")},errors};await db.collection("systemAuditLogs").add({action:"database_reset",performedBy:uid,performedAt:FieldValue.serverTimestamp(),deletedCounts:result.deleted,preservedCounts:result.preserved,status:result.status});res.status(errors.length?207:200).json(result);}catch(e){res.status(403).json({error:e instanceof Error?e.message:"Database reset failed."});}});
