import { useEffect, useState } from "react";
import { PageHeader } from "../components/PageHeader";
import { getDatabaseResetPreview, resetApplicationData, type ResetPreview } from "../services/databaseResetService";
const roles=["scert_admin","scert_viewer","diet_nodal_officer","agency_user","architecture_user","finance_officer","monitoring_officer"];
const names:Record<string,string>={workPackages:"Work Packages",financialTransactions:"Financial Transactions",scopeOfWorks:"Scopes",drawingPackages:"Architecture Drawings",communications:"Communications",documentAttachments:"Transactional Document Metadata",tenders:"Tenders",workOrders:"Work Orders",notifications:"Notifications",auditLogs:"Operational Audit Logs",users:"Operational Users",architectureUsers:"Architecture Users",architectureRegistrations:"Architecture Registrations",architectureAssignments:"Architecture Assignments",registrationRequests:"All Registrations",userAssignments:"User Assignments",dietAgencyAssignments:"DIET–Agency Assignments"};
export function AdminSettingsPage(){
 const[preview,setPreview]=useState<ResetPreview|null>(null),[stage,setStage]=useState<0|1|2>(0),[confirmation,setConfirmation]=useState(""),[busy,setBusy]=useState(false),[previewLoading,setPreviewLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){setPreviewLoading(true);try{setPreview(await getDatabaseResetPreview());}catch(e){setError(e instanceof Error?e.message:"Unable to load reset status.");}finally{setPreviewLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function reset(){setBusy(true);setError("");try{const result=await resetApplicationData();if(result.status!=="completed")throw new Error(`Reset completed with errors: ${result.errors.join(" ")}`);setNotice("Application data reset successfully. Phase I/II financial approvals were preserved.");setStage(0);setConfirmation("");await load();setTimeout(()=>location.reload(),1200);}catch(e){setError(e instanceof Error?e.message:"Database reset failed.");}finally{setBusy(false);}}
 return <><PageHeader eyebrow="Administration" title="Settings and master data" description="System configuration and protected administrative utilities."/>{error&&<div className="error-banner">{error}</div>}{notice&&<div className="success-banner">{notice}</div>}
 <section className="section-band"><div className="section-title"><h2>Configured user roles</h2><span>Foundation access model</span></div><div className="role-grid">{roles.map(role=><article className="role-card" key={role}><strong>{role.replaceAll("_"," ")}</strong></article>)}</div></section>
 <section className="section-band danger-zone"><div className="section-title"><div><span>Database Reset</span><h2>Database Management</h2></div><strong>Protected server-side utility</strong></div><div className="warning-banner"><strong>Danger Zone</strong><br/>Reset removes operational users and project transactions. Protected SCERT Admins, master data, system audit logs, and Phase I/II activity financial approvals are preserved.</div>{previewLoading&&<p className="muted-text">Loading reset preview...</p>}{preview&&<><h3>Will be preserved</h3><div className="detail-grid"><div><span>SCERT Admin users</span><strong>{preview.preserved.scertAdmins||0}</strong></div><div><span>DIET Master</span><strong>{preview.preserved.diets||0}</strong></div><div><span>Activity Master</span><strong>{(preview.preserved.activities||0)+(preview.preserved.activityMaster||0)}</strong></div><div><span>Phases</span><strong>{preview.preserved.phases||0}</strong></div><div><span>Agencies</span><strong>{preview.preserved.agencies||0}</strong></div><div><span>Phase I/II Activity Financial Approvals</span><strong>{preview.preserved.phase1And2ActivityFinancials||0}</strong></div></div><h3>Will be reset</h3><div className="detail-grid">{Object.entries(preview.deleted).filter(([key])=>names[key]).map(([key,value])=><div key={key}><span>{names[key]}</span><strong>{value}</strong></div>)}</div></>}
 <button className="primary-button danger-button" disabled={!preview?.enabled||previewLoading||busy} onClick={()=>setStage(1)}>Reset Application Data</button>{preview&&!preview.enabled&&<p className="muted-text">Database reset is disabled in this environment.</p>}</section>
 {stage>0&&<div className="reset-modal-backdrop" role="dialog" aria-modal="true"><section className="reset-modal"><h2>Reset Application Data?</h2><p>Operational users, registrations, assignments, Work Packages, transactions, Scope/Architecture records, tenders, and operational documents will be deleted. Phase I/II approved financial baselines and protected master data will remain.</p>{stage===1?<div className="form-actions"><button className="secondary-button" onClick={()=>setStage(0)}>Cancel</button><button className="primary-button danger-button" onClick={()=>setStage(2)}>Continue</button></div>:<><label>Type <strong>RESET DATABASE</strong> to continue<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoFocus/></label><div className="form-actions"><button className="secondary-button" disabled={busy} onClick={()=>setStage(0)}>Cancel</button><button className={`primary-button danger-button ${busy?"resetting":""}`} disabled={confirmation!=="RESET DATABASE"||busy} onClick={()=>void reset()}>{busy?"Resetting project data...":"Permanently Reset Data"}</button></div></>}</section></div>}</>;
}
