import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { useAuth } from "../contexts/AuthContext";
import { generateComparativeStatement } from "../services/financialEvaluationService";
import { createAwardRecommendation, createTenderAward, getAwardRecommendationsForTender } from "../services/tenderAwardService";
import { formatIndianCurrency } from "../utils/currency";
import { formatAboveBelowEstimate } from "../utils/financialEvaluation";
import type { TenderAwardRecommendation } from "../types";

export function AwardRecommendationPage(){
 const{tenderId=""}=useParams(),{profile}=useAuth(),role=profile?.systemRole||profile?.role,agency=role==="agency_user";
 const[data,setData]=useState<Awaited<ReturnType<typeof generateComparativeStatement>>|null>(null),[recs,setRecs]=useState<TenderAwardRecommendation[]>([]),[selected,setSelected]=useState(""),[amount,setAmount]=useState(""),[reason,setReason]=useState(""),[nonL1,setNonL1]=useState(""),[joint,setJoint]=useState(""),[awardNo,setAwardNo]=useState(""),[awardDate,setAwardDate]=useState(""),[finalValue,setFinalValue]=useState(""),[awardRemarks,setAwardRemarks]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){try{const[d,r]=await Promise.all([generateComparativeStatement(tenderId),getAwardRecommendationsForTender(tenderId)]);setData(d);setRecs(r);const active=r.find(x=>x.status!=="rejected");if(active){setSelected(active.recommendedFinancialBidId);setAmount(String(active.proposedAwardAmount));setReason(active.recommendationReason);setNonL1(active.nonL1Justification||"");setJoint(active.jointL1Justification||"");}else if(d.lowestBid){setSelected(d.lowestBid.id);setAmount(String(d.lowestBid.finalEvaluatedAmount));}}catch(e){setError(e instanceof Error?e.message:"Unable to load award workflow.");}}
 useEffect(()=>{void load();},[tenderId]);
 async function run(fn:()=>Promise<unknown>,message:string){setError("");try{await fn();await load();setNotice(message);}catch(e){setError(e instanceof Error?e.message:"Unable to update award workflow.");}}
 if(!data)return <>{error?<div className="error-banner">{error}</div>:<div className="empty-state">Loading award workflow...</div>}</>;
 const current=recs.find(x=>x.status!=="rejected"),bid=data.bidders.find(x=>x.id===selected),editable=agency&&(!current||["draft","revision_required"].includes(current.status));
 return <><PageHeader eyebrow="Phase 2I — eProc Punjab monitoring" title="AOC (Award of Contract) Record" description={data.tender.tenderNumber||data.tender.tenderTitle}/>{error&&<div className="error-banner">{error}</div>}{notice&&<div className="success-banner">{notice}</div>}<div className="notice-banner">Record the Award of Contract corresponding to the eProc Punjab tender result.</div>{data.tender.status!=="published"&&<div className="error-banner">The tender must be published before an AOC can be recorded.</div>}{data.tender.financialEvaluationStatus!=="approved"&&<div className="error-banner">The financial evaluation record must be verified before AOC recording.</div>}{bid&&!bid.isL1&&!bid.isJointLowest&&<div className="warning-banner">Selected contractor is not the lowest evaluated bidder. A justification is required.</div>}{bid?.isJointLowest&&<div className="warning-banner">Joint L1 selection requires an explicit justification.</div>}
 <section className="table-wrap"><div className="section-title"><h2>Financially Evaluated Bidders</h2><Link to={`/tenders/${tenderId}/comparative-statement`}>Comparative Statement</Link></div><table><thead><tr><th>Select</th><th>Rank</th><th>Contractor</th><th>Quoted</th><th>Evaluated</th><th>Comparison</th></tr></thead><tbody>{data.bidders.map(f=><tr key={f.id}><td><input type="radio" name="bid" disabled={!editable} checked={selected===f.id} onChange={()=>{setSelected(f.id);setAmount(String(f.finalEvaluatedAmount));}}/></td><td>{f.isJointLowest?"Joint L1":f.rank?`L${f.rank}`:"—"}</td><td>{f.contractorName} <small>{f.contractorCode}</small></td><td>{formatIndianCurrency(f.quotedAmount)}</td><td>{formatIndianCurrency(f.finalEvaluatedAmount)}</td><td>{formatAboveBelowEstimate(f.percentAboveBelowEstimate)}</td></tr>)}</tbody></table></section>
 {editable&&<section className="section-band agency-form"><label>Proposed Award Amount *<input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="agency-form-wide">Selection Reason *<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>{bid&&!bid.isL1&&!bid.isJointLowest&&<label className="agency-form-wide">Reason for selecting bidder other than L1 *<textarea value={nonL1} onChange={e=>setNonL1(e.target.value)}/></label>}{bid?.isJointLowest&&<label className="agency-form-wide">Joint L1 Selection Justification *<textarea value={joint} onChange={e=>setJoint(e.target.value)}/></label>}<div className="form-actions"><button className="primary-button" disabled={!bid||data.tender.status!=="published"||data.tender.financialEvaluationStatus!=="approved"} onClick={()=>bid&&void run(()=>createAwardRecommendation(tenderId,{financialBid:bid,proposedAwardAmount:Number(amount),recommendationReason:reason,nonL1Justification:nonL1,jointL1Justification:joint},current?.id),"Successful bidder selection saved.")}>Save Successful Bidder Selection</button></div></section>}
 {current&&<section className="section-band"><div className="section-title"><h2>Successful Bidder Selection</h2><span className="status-pill">{current.status==="approved"?"Legacy SCERT-approved":"Selected"}</span></div><div className="detail-grid"><div><span>Contractor</span><strong>{current.contractorName}</strong></div><div><span>Rank</span><strong>{current.financialRank?`L${current.financialRank}`:"—"}</strong></div><div><span>Proposed Amount</span><strong>{formatIndianCurrency(current.proposedAwardAmount)}</strong></div><div><span>Selection Reason</span><strong>{current.recommendationReason}</strong></div>{current.nonL1Justification&&<div><span>Non-L1 Justification</span><strong>{current.nonL1Justification}</strong></div>}{current.jointL1Justification&&<div><span>Joint-L1 Justification</span><strong>{current.jointL1Justification}</strong></div>}{current.scertRemarks&&<div><span>Historical SCERT Remarks</span><strong>{current.scertRemarks}</strong></div>}</div></section>}
 {agency&&current&&["draft","revision_required","approved"].includes(current.status)&&<section className="section-band agency-form"><div className="agency-form-wide section-title"><h2>Create Tender Award</h2></div><label>Award Number *<input value={awardNo} onChange={e=>setAwardNo(e.target.value)}/></label><label>Award Date *<input type="date" value={awardDate} onChange={e=>setAwardDate(e.target.value)}/></label><label>Final Contract Value *<input type="number" min="0" step="0.01" value={finalValue} onChange={e=>setFinalValue(e.target.value)}/></label><label className="agency-form-wide">Remarks{Number(finalValue)>data.tender.estimatedTenderValue?" *":""}<textarea value={awardRemarks} onChange={e=>setAwardRemarks(e.target.value)}/></label>{Number(finalValue)>data.tender.estimatedTenderValue&&<div className="warning-banner agency-form-wide">Final contract value is above the tender estimate. Remarks are required.</div>}<div className="form-actions"><button className="primary-button" onClick={()=>void run(async()=>{const awardId=await createTenderAward(current.id,{awardNumber:awardNo,awardDate,finalContractValue:Number(finalValue),remarks:awardRemarks});location.assign(`/tender-awards/${awardId}`);},"Tender award created and work package marked awarded.")}>Create Tender Award</button></div></section>}</>;
}
