import { FormEvent, useEffect, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { contractorCategoryOptions, contractorEntityTypeOptions } from "../constants/contractors";
import { punjabDistricts } from "../constants/punjabDistricts";
import { useAuth } from "../contexts/AuthContext";
import { checkContractorDuplicates, createContractor, getContractorById, updateContractor, type ContractorInput } from "../services/contractorService";
import { isValidGst, isValidPan, normalizeGst, normalizeMobile, normalizePan } from "../utils/contractorIdentifiers";
import type { ContractorCategory, ContractorEntityType } from "../types";

const empty: ContractorInput = { legalName: "", tradeName: "", entityType: "proprietorship", contractorCategories: [], registrationNumber: "", registrationAuthority: "", contractorClass: "", gstNumber: "", panNumber: "", contactPersonName: "", designation: "", mobile: "", alternateMobile: "", email: "", addressLine1: "", addressLine2: "", districtId: "", districtName: "", state: "Punjab", pinCode: "", active: true, remarks: "" };

export function ContractorFormPage() {
  const { id } = useParams(), navigate = useNavigate(), [params] = useSearchParams(), { profile } = useAuth(); const admin = (profile?.systemRole || profile?.role) === "scert_admin"; const [form, setForm] = useState<ContractorInput>(empty), [code, setCode] = useState(""), [errors, setErrors] = useState<Record<string,string>>({}), [warning, setWarning] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { if (!id) return; getContractorById(id).then((item) => { if (!item) return setError("Contractor not found."); setCode(item.contractorCode); setForm({ legalName:item.legalName,tradeName:item.tradeName||"",entityType:item.entityType,contractorCategories:item.contractorCategories||[],registrationNumber:item.registrationNumber||"",registrationAuthority:item.registrationAuthority||"",contractorClass:item.contractorClass||"",gstNumber:item.gstNumber||"",panNumber:item.panNumber||"",contactPersonName:item.contactPersonName,designation:item.designation||"",mobile:item.mobile,alternateMobile:item.alternateMobile||"",email:item.email||"",addressLine1:item.addressLine1,addressLine2:item.addressLine2||"",districtId:item.districtId||"",districtName:item.districtName||"",state:item.state||"Punjab",pinCode:item.pinCode||"",active:item.active,remarks:item.remarks||"" }); }); }, [id]);
  function validate(){const next:Record<string,string>={}; const mobile=normalizeMobile(form.mobile), alt=normalizeMobile(form.alternateMobile||""); if(!form.legalName.trim())next.legalName="Legal name is required.";if(!form.contractorCategories.length)next.contractorCategories="Select at least one category.";if(!form.contactPersonName.trim())next.contactPersonName="Contact person is required.";if(!/^\d{10}$/.test(mobile))next.mobile="Enter a valid 10-digit mobile number.";if(alt&&!/^\d{10}$/.test(alt))next.alternateMobile="Enter a valid 10-digit alternate mobile.";if(form.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))next.email="Enter a valid email.";if(!form.addressLine1.trim())next.addressLine1="Address is required.";if(form.pinCode&&!/^\d{6}$/.test(form.pinCode))next.pinCode="PIN code must contain six digits.";if(!isValidPan(form.panNumber||""))next.panNumber="Enter a valid PAN format.";if(!isValidGst(form.gstNumber||""))next.gstNumber="Enter a valid GST format.";setErrors(next);return !Object.keys(next).length;}
  async function save(e:FormEvent){e.preventDefault();setError("");setWarning("");if(!validate())return;const normalized={...form,mobile:normalizeMobile(form.mobile),alternateMobile:normalizeMobile(form.alternateMobile||""),panNumber:normalizePan(form.panNumber||""),gstNumber:normalizeGst(form.gstNumber||"")};setSaving(true);try{const duplicate=await checkContractorDuplicates(normalized,id);if(duplicate.strongDuplicate)throw new Error("A contractor with this tax identifier already exists.");if(duplicate.possibleDuplicate&&!window.confirm("A contractor with the same legal name and mobile may already exist. Continue saving?"))return;const result=id?await updateContractor(id,normalized):await createContractor(normalized),savedId=id||("id" in result?result.id:""),returnTo=params.get("returnTo");navigate(returnTo&&!id?`${returnTo}${returnTo.includes("?")?"&":"?"}contractorId=${savedId}`:`/contractors/${savedId}`);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save contractor.");}finally{setSaving(false);}}
  const field=(name:string,label:string,required=false,type="text")=><label>{label}{required?" *":""}<input type={type} value={String((form as unknown as Record<string,unknown>)[name]||"")} onChange={(e)=>setForm({...form,[name]:e.target.value})}/>{errors[name]&&<span className="field-error">{errors[name]}</span>}</label>;
  return <><PageHeader eyebrow="Contractor master" title={id?"Edit Contractor":"Add Contractor"} description={code?`Contractor Code: ${code}`:"A stable contractor code will be generated on save."}/>{error&&<div className="error-banner">{error}</div>}{warning&&<div className="notice-banner">{warning}</div>}<form className="section-band agency-form" onSubmit={save} noValidate>
    <h2 className="agency-form-wide">A. Basic Information</h2>{field("legalName","Legal Name",true)}{field("tradeName","Trade Name")}<label>Entity Type *<select value={form.entityType} onChange={(e)=>setForm({...form,entityType:e.target.value as ContractorEntityType})}>{contractorEntityTypeOptions.map((o)=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label><fieldset className="scope-picker"><legend>Contractor Categories *</legend>{contractorCategoryOptions.map((o)=><label className="checkbox-row" key={o.value}><input type="checkbox" checked={form.contractorCategories.includes(o.value)} onChange={()=>setForm({...form,contractorCategories:form.contractorCategories.includes(o.value)?form.contractorCategories.filter((v)=>v!==o.value):[...form.contractorCategories,o.value as ContractorCategory]})}/>{o.label}</label>)}{errors.contractorCategories&&<span className="field-error">{errors.contractorCategories}</span>}</fieldset>
    <h2 className="agency-form-wide">B. Registration Information</h2>{field("registrationNumber","Registration Number")}{field("registrationAuthority","Registration Authority")}{field("contractorClass","Contractor Class")}
    <h2 className="agency-form-wide">C. Tax Information</h2>{field("gstNumber","GST Number")}{field("panNumber","PAN Number")}
    <h2 className="agency-form-wide">D. Contact Information</h2>{field("contactPersonName","Contact Person Name",true)}{field("designation","Designation")}{field("mobile","Mobile",true,"tel")}{field("alternateMobile","Alternate Mobile",false,"tel")}{field("email","Email",false,"email")}
    <h2 className="agency-form-wide">E. Address</h2><label className="agency-form-wide">Address Line 1 *<textarea value={form.addressLine1} onChange={(e)=>setForm({...form,addressLine1:e.target.value})}/>{errors.addressLine1&&<span className="field-error">{errors.addressLine1}</span>}</label>{field("addressLine2","Address Line 2")}<label>District<select value={form.districtId} onChange={(e)=>{const d=punjabDistricts.find((x)=>x.id===e.target.value);setForm({...form,districtId:e.target.value,districtName:d?.name||""});}}><option value="">Select district</option>{punjabDistricts.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{field("state","State")}{field("pinCode","PIN Code")}
    <h2 className="agency-form-wide">F. Administrative</h2><label className="checkbox-row"><input type="checkbox" checked={form.active} disabled={!admin} onChange={(e)=>setForm({...form,active:e.target.checked})}/>Active</label><label className="agency-form-wide">Remarks<textarea value={form.remarks} onChange={(e)=>setForm({...form,remarks:e.target.value})}/></label><div className="form-actions split-actions"><Link className="secondary-button" to={id?`/contractors/${id}`:"/contractors"}>Cancel</Link><button className="primary-button" disabled={saving}>{saving?"Saving...":id?"Update Contractor":"Create Contractor"}</button></div>
  </form></>;
}
