import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { useAuth } from "../contexts/AuthContext";
import { contractorCategoryLabel, contractorEntityLabel } from "../constants/contractors";
import { blacklistContractor, deactivateContractor, getContractorById, reactivateContractor, removeContractorBlacklist } from "../services/contractorService";
import type { Contractor } from "../types";

const timestamp = (value: unknown) => value && typeof value === "object" && "toDate" in value && typeof value.toDate === "function" ? value.toDate().toLocaleString("en-IN") : "—";
export function ContractorDetailPage(){const{id=""}=useParams(),{profile}=useAuth();const admin=(profile?.systemRole||profile?.role)==="scert_admin";const agency=(profile?.systemRole||profile?.role)==="agency_user";const[item,setItem]=useState<Contractor|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState("");async function load(){try{setItem(await getContractorById(id));}catch(e){setError(e instanceof Error?e.message:"Unable to load contractor.");}}useEffect(()=>{void load();},[id]);const canEdit=admin||(agency&&Boolean(item?.sourceAgencyId&&(profile?.assignedAgencyIds||[]).includes(item.sourceAgencyId)));async function act(kind:string){let reason="",date="";if(kind==="blacklist"){reason=window.prompt("Blacklist reason:")||"";if(!reason)return;date=window.prompt("Blacklist date (YYYY-MM-DD):",new Date().toISOString().slice(0,10))||"";if(!date)return;}else{reason=window.prompt(kind==="remove"?"Reason for removing blacklist:":kind==="deactivate"?"Reason for deactivation:":"Reactivation remarks:")||"";if(!reason)return;date=new Date().toISOString().slice(0,10);}try{if(kind==="blacklist")await blacklistContractor(id,reason,date,reason);else if(kind==="remove")await removeContractorBlacklist(id,reason,date);else if(kind==="deactivate")await deactivateContractor(id,reason);else await reactivateContractor(id,reason);await load();setNotice("Contractor status updated.");}catch(e){setError(e instanceof Error?e.message:"Unable to update status.");}}
if(!item)return <><PageHeader title="Contractor detail"/>{error?<div className="error-banner">{error}</div>:<div className="empty-state">Loading contractor...</div>}</>;return <><header className="page-header page-header-actions"><div><span className="eyebrow">Contractor detail</span><h1>{item.legalName}</h1><p>{item.contractorCode}</p></div>{canEdit&&<Link className="primary-button" to={`/contractors/${id}/edit`}>Edit Contractor</Link>}</header>{notice&&<div className="success-banner">{notice}</div>}{error&&<div className="error-banner">{error}</div>}
<section className="section-band"><div className="section-title"><h2>Contractor Overview</h2><Link to="/contractors">Back to register</Link></div><div className="detail-grid"><div><span>Contractor Code</span><strong>{item.contractorCode}</strong></div><div><span>Legal Name</span><strong>{item.legalName}</strong></div><div><span>Trade Name</span><strong>{item.tradeName||"—"}</strong></div><div><span>Entity Type</span><strong>{contractorEntityLabel(item.entityType)}</strong></div><div><span>Categories</span><strong>{item.contractorCategories.map(contractorCategoryLabel).join(", ")}</strong></div><div><span>Status</span><strong>{item.blacklisted?"Blacklisted":item.active?"Active":"Inactive"}</strong></div></div></section>
<section className="section-band"><div className="section-title"><h2>Registration</h2></div><div className="detail-grid"><div><span>Registration Number</span><strong>{item.registrationNumber||"—"}</strong></div><div><span>Registration Authority</span><strong>{item.registrationAuthority||"—"}</strong></div><div><span>Contractor Class</span><strong>{item.contractorClass||"—"}</strong></div></div></section>
<section className="section-band"><div className="section-title"><h2>Tax Details</h2></div><div className="detail-grid"><div><span>GST</span><strong>{item.gstNumber||"—"}</strong></div><div><span>PAN</span><strong>{item.panNumber||"—"}</strong></div></div></section>
<section className="section-band"><div className="section-title"><h2>Contact</h2></div><div className="detail-grid"><div><span>Contact Person</span><strong>{item.contactPersonName}</strong></div><div><span>Designation</span><strong>{item.designation||"—"}</strong></div><div><span>Mobile</span><strong>{item.mobile}</strong></div><div><span>Alternate Mobile</span><strong>{item.alternateMobile||"—"}</strong></div><div><span>Email</span><strong>{item.email||"—"}</strong></div></div></section>
<section className="section-band"><div className="section-title"><h2>Address</h2></div><p>{[item.addressLine1,item.addressLine2,item.districtName,item.state,item.pinCode].filter(Boolean).join(", ")}</p></section>
<section className="section-band"><div className="section-title"><h2>Procurement History</h2></div><p>No tender participation recorded yet.</p></section>
<section className="section-band"><div className="section-title"><h2>Administrative History</h2></div><div className="detail-grid"><div><span>Created by</span><strong>{item.createdBy}</strong></div><div><span>Created at</span><strong>{timestamp(item.createdAt)}</strong></div><div><span>Updated by</span><strong>{item.updatedBy}</strong></div><div><span>Updated at</span><strong>{timestamp(item.updatedAt)}</strong></div><div><span>Blacklist status</span><strong>{item.blacklisted?item.blacklistReason||"Blacklisted":"Not blacklisted"}</strong></div></div>{admin&&<div className="table-actions">{item.active?<button className="link-button" onClick={()=>void act("deactivate")}>Deactivate</button>:<button className="link-button" onClick={()=>void act("reactivate")}>Reactivate</button>}{item.blacklisted?<button className="link-button" onClick={()=>void act("remove")}>Remove Blacklist</button>:<button className="link-button" onClick={()=>void act("blacklist")}>Blacklist Contractor</button>}</div>}</section></>}
