import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Plus } from "lucide-react";
import { StatCard } from "../components/StatCard";
import { useAuth } from "../contexts/AuthContext";
import { contractorCategoryLabel, contractorCategoryOptions, contractorEntityLabel, contractorEntityTypeOptions } from "../constants/contractors";
import { getContractors } from "../services/contractorService";
import { maskGst } from "../utils/contractorIdentifiers";
import type { Contractor } from "../types";

export function ContractorsPage() {
  const { profile } = useAuth(); const role = profile?.systemRole || profile?.role;
  const canCreate = role === "scert_admin" || role === "agency_user";
  const [items, setItems] = useState<Contractor[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [search, setSearch] = useState(""), [active, setActive] = useState("all"), [blacklisted, setBlacklisted] = useState("all"), [category, setCategory] = useState("all"), [entity, setEntity] = useState("all"), [district, setDistrict] = useState("all");
  useEffect(() => { getContractors().then(setItems).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load contractors.")).finally(() => setLoading(false)); }, []);
  const districts = [...new Set(items.map((item) => item.districtName).filter(Boolean))].sort();
  const filtered = useMemo(() => items.filter((item) => { const term = search.trim().toLowerCase(); return (!term || [item.contractorCode, item.legalName, item.tradeName, item.contactPersonName, item.mobile, item.districtName, role === "scert_admin" ? item.gstNumber : ""].join(" ").toLowerCase().includes(term)) && (active === "all" || item.active === (active === "active")) && (blacklisted === "all" || item.blacklisted === (blacklisted === "blacklisted")) && (category === "all" || item.contractorCategories.includes(category as never)) && (entity === "all" || item.entityType === entity) && (district === "all" || item.districtName === district); }), [items, search, active, blacklisted, category, entity, district, role]);
  return <><header className="page-header page-header-actions"><div><span className="eyebrow">Procurement master</span><h1>Private Contractors & Suppliers</h1><p>Master register of private contractors and suppliers participating in Centre of Excellence procurement and civil works.</p></div>{canCreate && <Link className="primary-button" to="/contractors/new"><Plus size={18}/>Add Contractor</Link>}</header>
    <div className="stat-grid"><StatCard label="Total Contractors" value={items.length}/><StatCard label="Active Contractors" value={items.filter((item) => item.active).length}/><StatCard label="Inactive Contractors" value={items.filter((item) => !item.active).length}/><StatCard label="Blacklisted Contractors" value={items.filter((item) => item.blacklisted).length}/></div>
    {error && <div className="error-banner">{error}</div>}
    <section className="filters package-filters"><label>Search<input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Code, name, contact, mobile, district"/></label><label>Status<select value={active} onChange={(e) => setActive(e.target.value)}><option value="all">All</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label>Blacklist<select value={blacklisted} onChange={(e) => setBlacklisted(e.target.value)}><option value="all">All</option><option value="blacklisted">Blacklisted</option><option value="clear">Not Blacklisted</option></select></label><label>Category<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="all">All</option>{contractorCategoryOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Entity Type<select value={entity} onChange={(e) => setEntity(e.target.value)}><option value="all">All</option>{contractorEntityTypeOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>District<select value={district} onChange={(e) => setDistrict(e.target.value)}><option value="all">All</option>{districts.map((item) => <option key={item}>{item}</option>)}</select></label></section>
    <section className="table-wrap"><div className="section-title"><h2>Contractor register</h2><span>{loading ? "Loading..." : `${filtered.length} contractors`}</span></div>{!loading && !items.length ? <div className="empty-state">No private contractors have been added yet.{canCreate && <div><Link to="/contractors/new">Add Contractor</Link></div>}</div> : <table><thead><tr><th>Contractor Code</th><th>Legal Name</th><th>Trade Name</th><th>Category</th><th>Entity Type</th><th>District</th><th>Contact Person</th><th>Mobile</th><th>GST</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><Link to={`/contractors/${item.id}`}>{item.contractorCode}</Link></td><td>{item.legalName}</td><td>{item.tradeName || "—"}</td><td>{item.contractorCategories.map(contractorCategoryLabel).join(", ")}</td><td>{contractorEntityLabel(item.entityType)}</td><td>{item.districtName || "—"}</td><td>{item.contactPersonName}</td><td>{item.mobile}</td><td>{maskGst(item.gstNumber)}</td><td><span className={`status-pill ${item.blacklisted || !item.active ? "delayed" : "completed"}`}>{item.blacklisted ? "Blacklisted" : item.active ? "Active" : "Inactive"}</span></td><td><Link className="link-button" to={`/contractors/${item.id}`}>View</Link></td></tr>)}</tbody></table>}</section>
  </>;
}
