import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { StatCard } from "../components/StatCard";
import { useAuth } from "../contexts/AuthContext";
import { approveFinancialEvaluation, createOrUpdateFinancialBid, generateComparativeStatement, openFinancialBids, returnFinancialEvaluationForRevision, submitFinancialEvaluation } from "../services/financialEvaluationService";
import { formatIndianCurrency } from "../utils/currency";
import { formatAboveBelowEstimate } from "../utils/financialEvaluation";
import type { Tender, TenderBid, TenderFinancialBid } from "../types";

type View={tender:Tender;qualifiedBids:TenderBid[];ineligibleBids:TenderBid[];bidders:TenderFinancialBid[];tieStatus:boolean;lowestBid:TenderFinancialBid|null;summary:{financialBasis:number;bidCount:number;lowestAmount:number}};
export function FinancialEvaluationPage({comparisonOnly=false}:{comparisonOnly?:boolean}){
 const{tenderId=""}=useParams(),{profile}=useAuth(),role=profile?.systemRole||profile?.role,admin=role==="scert_admin",agency=role==="agency_user";
 const[data,setData]=useState<View|null>(null),[amounts,setAmounts]=useState<Record<string,string>>({}),[remarks,setRemarks]=useState<Record<string,string>>({}),[error,setError]=useState(""),[notice,setNotice]=useState(""),[saving,setSaving]=useState("");
 async function load(){try{const result=await generateComparativeStatement(tenderId);setData(result);setAmounts(Object.fromEntries(result.qualifiedBids.map(b=>[b.id,String(result.bidders.find(f=>f.tenderBidId===b.id)?.quotedAmount??"")])));}catch(e){setError(e instanceof Error?e.message:"Unable to load financial evaluation.");}}
 useEffect(()=>{void load();},[tenderId]);
 async function run(action:()=>Promise<void>,message:string){setError("");try{await action();await load();setNotice(message);}catch(e){setError(e instanceof Error?e.message:"Unable to update financial evaluation.");}finally{setSaving("");}}
 async function saveBid(bid:TenderBid){const value=Number(amounts[bid.id]);if(!Number.isFinite(value)||value<0)return setError("Enter a valid quoted amount.");const existing=data?.bidders.find(x=>x.tenderBidId===bid.id),reason=admin&&existing&&existing.quotedAmount!==value?window.prompt("SCERT correction reason:")||"":"";if(admin&&existing&&existing.quotedAmount!==value&&!reason)return;setSaving(bid.id);await run(()=>createOrUpdateFinancialBid(tenderId,bid.id,value,remarks[bid.id]||"",reason),"Financial amount saved and rankings recalculated.");}
 if(!data)return <>{error?<div className="error-banner">{error}</div>:<div className="empty-state">Loading financial evaluation...</div>}</>;
 const{tender,qualifiedBids,ineligibleBids,bidders,tieStatus,lowestBid}=data,status=tender.financialEvaluationStatus||"not_started",editable=admin||agency&&["in_progress","revision_required"].includes(status),opened=Boolean(tender.financialBidsOpenedAt)||status!=="not_started";
 return <><PageHeader eyebrow="Phase 2H" title={comparisonOnly?"Comparative Statement":"Financial Bid Evaluation"} description={tender.tenderNumber||tender.tenderTitle}/>{error&&<div className="error-banner">{error}</div>}{notice&&<div className="success-banner">{notice}</div>}
 <div className="table-actions"><Link className="secondary-button" to={comparisonOnly?`/tenders/${tenderId}/financial-evaluation`:`/tenders/${tenderId}/comparative-statement`}>{comparisonOnly?"Financial Entry":"View Comparative Statement"}</Link>{!opened&&(admin||agency)&&<button className="primary-button" onClick={()=>{const remarks=window.prompt("Financial bid opening remarks:")||"",override=window.prompt("If opening is early or the scheduled date is missing, enter override reason:")||"";void run(()=>openFinancialBids(tenderId,remarks,override),"Financial bids opened.");}}>Open Financial Bids</button>}{!comparisonOnly&&(admin||agency)&&["in_progress","revision_required"].includes(status)&&<button className="primary-button" onClick={()=>void run(()=>submitFinancialEvaluation(tenderId,window.confirm("Acknowledge any equal/joint-lowest bid warning?")),"Financial evaluation submitted to SCERT.")}>Submit for SCERT Review</button>}{admin&&status==="submitted_for_review"&&<><button className="secondary-button" onClick={()=>{const r=window.prompt("Revision remarks:")||"";if(r)void run(()=>returnFinancialEvaluationForRevision(tenderId,r),"Returned for revision.");}}>Return for Revision</button><button className="primary-button" onClick={()=>void run(()=>approveFinancialEvaluation(tenderId),"Financial evaluation approved. No award has been made.")}>Approve Financial Evaluation</button></>}</div>
 <div className="stat-grid compact-stats"><StatCard label="Tender Estimated Value" value={formatIndianCurrency(tender.estimatedTenderValue)}/><StatCard label="Technically Qualified" value={qualifiedBids.length}/><StatCard label="Financial Bids Entered" value={bidders.length}/><StatCard label="Evaluation Status" value={status.replaceAll("_"," ")}/>{lowestBid&&<><StatCard label={tieStatus?"Joint Lowest Amount":"L1 Amount"} value={formatIndianCurrency(lowestBid.finalEvaluatedAmount)}/><StatCard label="Difference from Estimate" value={formatAboveBelowEstimate(lowestBid.percentAboveBelowEstimate)}/></>}</div>
 {qualifiedBids.length===1&&<div className="warning-banner">Only one technically qualified financial bid is available.</div>}{tieStatus&&<div className="warning-banner">Multiple bidders have identical evaluated financial amounts. Joint-lowest bidders require SCERT review.</div>}{lowestBid&&lowestBid.finalEvaluatedAmount>tender.estimatedTenderValue&&<div className="error-banner">Lowest evaluated bid is above the tender estimate.</div>}
 <section className="section-band"><div className="section-title"><h2>Tender Summary</h2></div><div className="detail-grid"><div><span>Tender</span><strong>{tender.tenderTitle}</strong></div><div><span>DIET</span><strong>{tender.dietName}</strong></div><div><span>Executing Agency</span><strong>{tender.executingAgencyName}</strong></div><div><span>Work Package</span><strong>{tender.workPackageCode}</strong></div><div><span>Technical Evaluation</span><strong>{tender.technicalEvaluationStatus||"not started"}</strong></div><div><span>Financial Bids Opened</span><strong>{opened?"Yes":"No"}</strong></div></div></section>
 <section className="table-wrap"><div className="section-title"><h2>{comparisonOnly?"Comparative Statement":"Qualified Financial Bids"}</h2><span>{bidders.length} entered</span></div><table><thead><tr><th>Rank</th><th>Contractor</th><th>Code</th><th>Technical Status</th><th>Quoted Amount</th><th>Evaluated Amount</th><th>Difference</th><th>% Above/Below</th><th>Status</th>{!comparisonOnly&&<th>Actions</th>}</tr></thead><tbody>{qualifiedBids.map(b=>{const f=bidders.find(x=>x.tenderBidId===b.id);return <tr key={b.id}><td>{f?.isJointLowest?"Joint L1":f?.rank?`L${f.rank}`:"—"}</td><td>{b.contractorName}</td><td>{b.contractorCode}</td><td>Qualified</td><td>{comparisonOnly?f?formatIndianCurrency(f.quotedAmount):"Not entered":<input type="number" min="0" step="0.01" disabled={!editable} value={amounts[b.id]||""} onChange={e=>setAmounts({...amounts,[b.id]:e.target.value})}/>}</td><td>{f?formatIndianCurrency(f.finalEvaluatedAmount):"—"}</td><td>{f?formatIndianCurrency(f.amountDifferenceFromEstimate):"—"}</td><td>{f?formatAboveBelowEstimate(f.percentAboveBelowEstimate):"—"}</td><td>{f?.financialBidStatus.replaceAll("_"," ")||"Not entered"}</td>{!comparisonOnly&&<td>{editable&&<button className="link-button" disabled={saving===b.id} onClick={()=>void saveBid(b)}>{saving===b.id?"Saving...":"Save Amount"}</button>}</td>}</tr>})}{!qualifiedBids.length&&<tr><td colSpan={comparisonOnly?9:10}>No technically qualified bidders are available for financial evaluation.</td></tr>}</tbody></table></section>
 {ineligibleBids.length>0&&<section className="table-wrap"><div className="section-title"><h2>Not Eligible for Financial Opening</h2></div><table><thead><tr><th>Contractor</th><th>Code</th><th>Status</th><th>Reason</th></tr></thead><tbody>{ineligibleBids.map(b=><tr key={b.id}><td>{b.contractorName}</td><td>{b.contractorCode}</td><td>{b.withdrawn?"Withdrawn":"Not qualified"}</td><td>{b.disqualificationReason||b.technicalRemarks||"Not eligible after technical evaluation"}</td></tr>)}</tbody></table></section>}
 <section className="section-band"><h2>Documents</h2><p className="muted-text">Financial bid opening statements, BOQs, and committee proceedings will be added in a future document-management phase.</p></section></>;
}
export function ComparativeStatementPage(){return <FinancialEvaluationPage comparisonOnly/>;}

