import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Plus, X } from "lucide-react";
import { useAuth } from "../contexts/AuthContext";
import { getActivityMaster } from "../lib/firestore";
import { getAssignmentsForAgency, getAssignmentsForDiet, getDietAgencyAssignments } from "../services/dietAgencyAssignmentService";
import { approveScopeOfWork, createScopeOfWork, getScopeOfWorks, getScopesForAgency, getScopesForDiet, returnScopeForRevision, reviewScopeOfWork, submitScopeOfWork, updateScopeOfWork } from "../services/scopeOfWorkService";
import { labelScope, scopeCategoryOptions } from "../constants/projectExecution";
import type { ActivityMaster, DietAgencyAssignment, ScopeCategory, ScopeOfWork } from "../types";

const empty={assignmentId:"",scopeTitle:"",scopeDescription:"",scopeCategories:[] as ScopeCategory[],activityIds:[] as string[],remarks:""};
const statusLabel=(value:string)=>value.replaceAll("_"," ");
export function ScopesPage(){const{profile}=useAuth(),role=profile?.systemRole||profile?.role,admin=role==="scert_admin",dietUser=role==="diet_nodal_officer";const[params]=useSearchParams();const[items,setItems]=useState<ScopeOfWork[]>([]),[assignments,setAssignments]=useState<DietAgencyAssignment[]>([]),[activities,setActivities]=useState<ActivityMaster[]>([]),[form,setForm]=useState({...empty,assignmentId:params.get("assignmentId")||""}),[open,setOpen]=useState(params.get("create")==="1"),[editing,setEditing]=useState<ScopeOfWork|null>(null),[viewing,setViewing]=useState<ScopeOfWork|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false);
async function load(){try{const dietIds=profile?.assignedDietIds||[],agencyIds=profile?.assignedAgencyIds||[];const all=admin||role==="scert_viewer";const scopeReq=all?getScopeOfWorks():dietUser?Promise.all(dietIds.map(getScopesForDiet)).then(x=>x.flat()):role==="agency_user"?Promise.all(agencyIds.map(getScopesForAgency)).then(x=>x.flat()):Promise.resolve([]);const assignmentReq=all?getDietAgencyAssignments():dietUser?Promise.all(dietIds.map(getAssignmentsForDiet)).then(x=>x.flat()):role==="agency_user"?Promise.all(agencyIds.map(getAssignmentsForAgency)).then(x=>x.flat()):Promise.resolve([]);const[s,a,m]=await Promise.all([scopeReq,assignmentReq,getActivityMaster()]);setItems([...new Map(s.map(x=>[x.id,x])).values()]);setAssignments([...new Map(a.map(x=>[x.id,x])).values()]);setActivities(m.filter(x=>x.active!==false));}catch(e){setError(e instanceof Error?e.message:"Unable to load scopes.");}}useEffect(()=>{if(profile)void load();},[profile]);
const canCreate=admin||dietUser;function edit(item:ScopeOfWork){setEditing(item);setOpen(true);setForm({assignmentId:item.dietAgencyAssignmentId,scopeTitle:item.scopeTitle,scopeDescription:item.scopeDescription,scopeCategories:item.scopeCategories||[],activityIds:item.activityIds||[],remarks:item.remarks||""});}async function save(e:FormEvent){e.preventDefault();const assignment=assignments.find(x=>x.id===form.assignmentId);if(!assignment)return setError("Select an active assignment.");setSaving(true);setError("");try{const input={assignment,scopeTitle:form.scopeTitle,scopeDescription:form.scopeDescription,scopeCategories:form.scopeCategories,activityIds:form.activityIds,remarks:form.remarks};editing?await updateScopeOfWork(editing.id,input):await createScopeOfWork(input);setOpen(false);setEditing(null);setForm(empty);await load();setNotice("Scope saved successfully.");}catch(e){setError(e instanceof Error?e.message:"Unable to save scope.");}finally{setSaving(false);}}
async function act(kind:string,item:ScopeOfWork){try{if(kind==="submit")await submitScopeOfWork(item.id);else if(kind==="review")await reviewScopeOfWork(item.id);else if(kind==="approve")await approveScopeOfWork(item.id);else{const remarks=window.prompt("Revision remarks:")||"";if(!remarks)return;await returnScopeForRevision(item.id,remarks);}await load();setNotice("Scope workflow updated.");}catch(e){setError(e instanceof Error?e.message:"Unable to update scope.");}}
return <><header className="page-header page-header-actions"><div><span className="eyebrow">Execution planning</span><h1>{admin?"Scope Reviews":"Scope of Work"}</h1><p>DIET-prepared work scope under active executing-agency assignments.</p></div>{canCreate&&<button className="primary-button" onClick={()=>{setEditing(null);setForm({...empty,assignmentId:params.get("assignmentId")||""});setOpen(true);}}><Plus size={18}/>Create Scope</button>}</header>{notice&&<div className="success-banner">{notice}</div>}{error&&<div className="error-banner">{error}</div>}
{open&&canCreate&&<section className="section-band"><div className="section-title"><h2>{editing?"Edit Scope":"Create Scope of Work"}</h2><button className="secondary-button" onClick={()=>setOpen(false)}><X size={16}/>Close</button></div><form className="agency-form" onSubmit={save}><label>Executing Agency Assignment *<select value={form.assignmentId} disabled={Boolean(editing)} onChange={e=>setForm({...form,assignmentId:e.target.value})}><option value="">Select active assignment</option>{assignments.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.dietName} — {x.executingAgencyName}</option>)}</select></label><label>Scope Title *<input value={form.scopeTitle} onChange={e=>setForm({...form,scopeTitle:e.target.value})}/></label><label className="agency-form-wide">Scope Description *<textarea rows={3} value={form.scopeDescription} onChange={e=>setForm({...form,scopeDescription:e.target.value})}/></label><fieldset className="scope-picker"><legend>Scope Categories *</legend>{scopeCategoryOptions.map(x=><label className="checkbox-row" key={x.value}><input type="checkbox" checked={form.scopeCategories.includes(x.value)} onChange={()=>setForm({...form,scopeCategories:form.scopeCategories.includes(x.value)?form.scopeCategories.filter(v=>v!==x.value):[...form.scopeCategories,x.value]})}/>{x.label}</label>)}</fieldset><fieldset className="activity-picker"><legend>Activities *</legend>{activities.map(x=><label className="checkbox-row" key={x.id}><input type="checkbox" checked={form.activityIds.includes(x.id)} onChange={()=>setForm({...form,activityIds:form.activityIds.includes(x.id)?form.activityIds.filter(v=>v!==x.id):[...form.activityIds,x.id]})}/>{x.code} — {x.activityHead} — {x.subActivity}</label>)}</fieldset><label className="agency-form-wide">Remarks<textarea value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></label><div className="form-actions"><button className="primary-button" disabled={saving}>{saving?"Saving...":"Save Draft"}</button></div></form></section>}
{viewing&&<section className="section-band"><div className="section-title"><h2>{viewing.scopeTitle}</h2><button className="secondary-button" onClick={()=>setViewing(null)}>Close</button></div><p>{viewing.scopeDescription}</p><div className="detail-grid"><div><span>DIET</span><strong>{viewing.dietName}</strong></div><div><span>Agency</span><strong>{viewing.executingAgencyName}</strong></div><div><span>Categories</span><strong>{viewing.scopeCategories.map(labelScope).join(", ")}</strong></div><div><span>Activities</span><strong>{viewing.activityIds.length}</strong></div></div></section>}
<section className="table-wrap"><table><thead><tr><th>DIET</th><th>Phase</th><th>Executing Agency</th><th>Scope Title</th><th>Categories</th><th>Activities</th><th>Prepared By</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(item=>{const dietMayEdit=dietUser&&["draft","revision_required"].includes(item.status);return <tr key={item.id}><td>{item.dietName}</td><td>{item.phaseName}</td><td>{item.executingAgencyName}</td><td>{item.scopeTitle}</td><td>{item.scopeCategories.map(labelScope).join(", ")}</td><td>{item.activityIds.length}</td><td>{item.preparedBy}</td><td><span className="status-pill">{statusLabel(item.status)}</span></td><td><div className="table-actions"><button className="link-button" onClick={()=>setViewing(item)}>View</button>{(admin||dietMayEdit)&&<button className="link-button" onClick={()=>edit(item)}>Edit</button>}{dietMayEdit&&<button className="link-button" onClick={()=>void act("submit",item)}>Submit</button>}{admin&&item.status==="submitted"&&<button className="link-button" onClick={()=>void act("review",item)}>Review</button>}{admin&&["submitted","under_review"].includes(item.status)&&<button className="link-button" onClick={()=>void act("approve",item)}>Approve</button>}{admin&&["submitted","under_review"].includes(item.status)&&<button className="link-button" onClick={()=>void act("return",item)}>Return for Revision</button>}</div></td></tr>})}{!items.length&&<tr><td colSpan={9}>No scope-of-work records are available.</td></tr>}</tbody></table></section></>}
