import { getPhaseSequence, requiresPrePabWorkflow } from "../constants/projectPhases";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { useAuth } from "../contexts/AuthContext";
import { procurementMethodLabels, tenderTypeLabels } from "../constants/tenders";
import { createTender, getTenderById, toInputDate, updateTender, type TenderInput } from "../services/tenderService";
import { getWorkPackage, getWorkPackages, getWorkPackagesForAgency } from "../services/workPackageService";
import { formatIndianCurrency } from "../utils/currency";
import { calculateFundingShare, getPackageFinancialBasis } from "../utils/fundingCalculations";
import type { ProcurementMethod, TenderType, WorkPackage } from "../types";

type Form = Record<string,string>;
const initial:Form={workPackageId:"",tenderTitle:"",tenderNumber:"",nitNumber:"",tenderType:"e_tender",procurementMethod:"two_bid_system",estimatedTenderValue:"",valueVariationRemarks:"",emdAmount:"",tenderFee:"",bidValidityDays:"",noticeDate:"",publicationDate:"",documentDownloadStartDate:"",bidSubmissionStartDate:"",bidSubmissionEndDate:"",preBidMeetingDate:"",technicalBidOpeningDate:"",financialBidOpeningDate:"",completionPeriodValue:"",completionPeriodUnit:"months",tenderPortalName:"",tenderPortalReference:"",tenderPortalUrl:"",publicationRemarks:"",internalRemarks:""};
const dateFields=["noticeDate","publicationDate","documentDownloadStartDate","bidSubmissionStartDate","bidSubmissionEndDate","preBidMeetingDate","technicalBidOpeningDate","financialBidOpeningDate"];
export function TenderFormPage(){
  const{id}=useParams(),[params]=useSearchParams(),navigate=useNavigate(),{profile}=useAuth(),[packages,setPackages]=useState<WorkPackage[]>([]),[form,setForm]=useState<Form>(initial),[error,setError]=useState(""),[saving,setSaving]=useState(false);
  const role=profile?.systemRole||profile?.role,editing=Boolean(id);
  useEffect(()=>{if(!profile)return;const load=role==="agency_user"?Promise.all((profile.assignedAgencyIds||[]).map(getWorkPackagesForAgency)).then(x=>x.flat()):getWorkPackages();load.then(async items=>{const unique=[...new Map(items.map(x=>[x.id,x])).values()];setPackages(unique);if(id){const tender=await getTenderById(id);if(!tender)throw new Error("Tender not found.");const wp=unique.find(x=>x.id===tender.workPackageId)||await getWorkPackage(tender.workPackageId);if(wp)setPackages(old=>[...new Map([...old,wp].map(x=>[x.id,x])).values()]);const next:{[key:string]:string}={...initial};for(const key of Object.keys(initial))next[key]=String((tender as unknown as Record<string,unknown>)[key]??"");for(const key of dateFields)next[key]=toInputDate((tender as unknown as Record<string,unknown>)[key]);next.workPackageId=tender.workPackageId;setForm(next);}else{const selected=params.get("workPackageId")||"";const wp=unique.find(x=>x.id===selected);setForm(old=>({...old,workPackageId:selected,tenderTitle:wp?.packageTitle||"",estimatedTenderValue:wp?String(getPackageFinancialBasis(wp)):""}));}}).catch(e=>setError(e instanceof Error?e.message:"Unable to load tender form."));},[profile,id]);
  const wp=useMemo(()=>packages.find(x=>x.id===form.workPackageId)||null,[packages,form.workPackageId]),basis=wp?getPackageFinancialBasis(wp):0,value=Number(form.estimatedTenderValue||0),variation=value-basis,shares=calculateFundingShare(value);
  function set(key:string,value:string){setForm(old=>({...old,[key]:value}));if(key==="workPackageId"){const selected=packages.find(x=>x.id===value);if(selected)setForm(old=>({...old,workPackageId:value,tenderTitle:old.tenderTitle||selected.packageTitle,estimatedTenderValue:String(getPackageFinancialBasis(selected))}));}}
  function input():TenderInput{if(!wp)throw new Error("Select an approved work package.");const n=(key:string)=>form[key]===""?undefined:Number(form[key]);return{workPackage:wp,tenderTitle:form.tenderTitle,tenderNumber:form.tenderNumber,nitNumber:form.nitNumber,tenderType:form.tenderType as TenderType,procurementMethod:form.procurementMethod as ProcurementMethod,estimatedTenderValue:Number(form.estimatedTenderValue),valueVariationRemarks:form.valueVariationRemarks,emdAmount:n("emdAmount"),tenderFee:n("tenderFee"),bidValidityDays:n("bidValidityDays"),noticeDate:form.noticeDate,publicationDate:form.publicationDate,documentDownloadStartDate:form.documentDownloadStartDate,bidSubmissionStartDate:form.bidSubmissionStartDate,bidSubmissionEndDate:form.bidSubmissionEndDate,preBidMeetingDate:form.preBidMeetingDate,technicalBidOpeningDate:form.technicalBidOpeningDate,financialBidOpeningDate:form.financialBidOpeningDate,completionPeriodValue:n("completionPeriodValue"),completionPeriodUnit:form.completionPeriodUnit as "days"|"months",tenderPortalName:form.tenderPortalName,tenderPortalReference:form.tenderPortalReference,tenderPortalUrl:form.tenderPortalUrl,publicationRemarks:form.publicationRemarks,internalRemarks:form.internalRemarks};}
  async function save(e:FormEvent){e.preventDefault();setError("");setSaving(true);try{const payload=input();const target=id?(await updateTender(id,payload),id):await createTender(payload);navigate(`/tenders/${target}`);}catch(e){setError(e instanceof Error?e.message:"Unable to save tender.");}finally{setSaving(false);}}
  const approved=packages.filter(x=>x.status==="approved_for_tender"||x.id===form.workPackageId);
  return <><PageHeader eyebrow="Phase 2F" title={editing?"Edit Tender / NIT":"Create Tender / NIT"} description="Prepare procurement information from an approved work package."/>{error&&<div className="error-banner">{error}</div>}<form className="section-band agency-form" onSubmit={save}>
    <div className="agency-form-wide section-title"><h2>A. Source Work Package</h2><Link to="/tenders">Back to tenders</Link></div><label className="agency-form-wide">Approved Work Package<select required disabled={editing} value={form.workPackageId} onChange={e=>set("workPackageId",e.target.value)}><option value="">Select package</option>{approved.map(x=><option key={x.id} value={x.id}>{x.packageCode} — {x.packageTitle}</option>)}</select></label>{wp&&<div className="detail-grid agency-form-wide"><div><span>DIET</span><strong>{wp.dietName}</strong></div><div><span>Phase</span><strong>{wp.phaseName}</strong></div><div><span>Executing Agency</span><strong>{wp.executingAgencyName}</strong></div>{requiresPrePabWorkflow(getPhaseSequence(wp))&&<div><span>Scope of Work</span><strong>{wp.scopeOfWorkTitle||"Legacy package"}</strong></div>}<div><span>Approved Financial Basis</span><strong>{formatIndianCurrency(basis)}</strong></div></div>}
    <div className="agency-form-wide section-title"><h2>B. Tender Information</h2></div><label>Tender Title<input required value={form.tenderTitle} onChange={e=>set("tenderTitle",e.target.value)}/></label><label>Tender Number<input value={form.tenderNumber} onChange={e=>set("tenderNumber",e.target.value)}/></label><label>NIT Number<input value={form.nitNumber} onChange={e=>set("nitNumber",e.target.value)}/></label><label>Tender Type<select value={form.tenderType} onChange={e=>set("tenderType",e.target.value)}>{Object.entries(tenderTypeLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Procurement Method<select value={form.procurementMethod} onChange={e=>set("procurementMethod",e.target.value)}>{Object.entries(procurementMethodLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
    <div className="agency-form-wide section-title"><h2>C. Financial Information</h2></div><label>Estimated Tender Value<input required min="0" step="0.01" type="number" value={form.estimatedTenderValue} onChange={e=>set("estimatedTenderValue",e.target.value)}/></label><label>EMD Amount<input min="0" step="0.01" type="number" value={form.emdAmount} onChange={e=>set("emdAmount",e.target.value)}/></label><label>Tender Fee<input min="0" step="0.01" type="number" value={form.tenderFee} onChange={e=>set("tenderFee",e.target.value)}/></label><label>Bid Validity Days<input min="0" type="number" value={form.bidValidityDays} onChange={e=>set("bidValidityDays",e.target.value)}/></label><div className="detail-grid agency-form-wide"><div><span>Difference</span><strong>{formatIndianCurrency(variation)}</strong></div><div><span>Difference %</span><strong>{basis?(variation/basis*100).toFixed(2):"0.00"}%</strong></div><div><span>Centre Share 60%</span><strong>{formatIndianCurrency(shares.centralShare)}</strong></div><div><span>State Share 40%</span><strong>{formatIndianCurrency(shares.stateShare)}</strong></div></div>{variation!==0&&<label className="agency-form-wide">Value Variation Remarks<textarea required rows={3} value={form.valueVariationRemarks} onChange={e=>set("valueVariationRemarks",e.target.value)}/></label>}
    <div className="agency-form-wide section-title"><h2>D. Tender Timeline</h2></div>{[["noticeDate","Notice Date"],["publicationDate","Publication Date"],["documentDownloadStartDate","Document Download Start Date"],["bidSubmissionStartDate","Bid Submission Start Date"],["bidSubmissionEndDate","Bid Submission End Date"],["preBidMeetingDate","Pre-Bid Meeting Date"],["technicalBidOpeningDate","Technical Bid Opening Date"],["financialBidOpeningDate","Financial Bid Opening Date"]].map(([key,label])=><label key={key}>{label}<input type="date" value={form[key]} onChange={e=>set(key,e.target.value)}/></label>)}
    <div className="agency-form-wide section-title"><h2>E. Completion Period</h2></div><label>Completion Period Value<input min="0" type="number" value={form.completionPeriodValue} onChange={e=>set("completionPeriodValue",e.target.value)}/></label><label>Unit<select value={form.completionPeriodUnit} onChange={e=>set("completionPeriodUnit",e.target.value)}><option value="days">Days</option><option value="months">Months</option></select></label>
    <div className="agency-form-wide section-title"><h2>F. Tender Portal</h2></div><label>Tender Portal Name<input value={form.tenderPortalName} onChange={e=>set("tenderPortalName",e.target.value)}/></label><label>Tender Portal Reference<input value={form.tenderPortalReference} onChange={e=>set("tenderPortalReference",e.target.value)}/></label><label className="agency-form-wide">Tender Portal URL<input type="url" value={form.tenderPortalUrl} onChange={e=>set("tenderPortalUrl",e.target.value)}/></label>
    <div className="agency-form-wide section-title"><h2>G. Remarks</h2></div><label>Publication Remarks<textarea rows={3} value={form.publicationRemarks} onChange={e=>set("publicationRemarks",e.target.value)}/></label><label>Internal Remarks<textarea rows={3} value={form.internalRemarks} onChange={e=>set("internalRemarks",e.target.value)}/></label><div className="form-actions"><button className="primary-button" disabled={saving}>{saving?"Saving...":"Save Draft"}</button></div>
  </form></>;
}
