import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { getTenderAwardById } from "../services/tenderAwardService";
import { createWorkOrder, getWorkOrdersForAward } from "../services/workOrderService";
import { formatIndianCurrency } from "../utils/currency";
import type { TenderAward, WorkOrder } from "../types";
export function TenderAwardDetailPage(){const{id=""}=useParams(),[award,setAward]=useState<TenderAward|null>(null),[orders,setOrders]=useState<WorkOrder[]>([]),[form,setForm]=useState({workOrderNumber:"",workOrderDate:"",commencementDate:"",completionPeriodValue:"",completionPeriodUnit:"months" as "days"|"months",performanceSecurityAmount:"",performanceSecurityPercent:"",securityDepositPercent:"",retentionPercent:"",agreementNumber:"",agreementDate:"",remarks:""}),[error,setError]=useState(""),[notice,setNotice]=useState("");async function load(){try{const[a,o]=await Promise.all([getTenderAwardById(id),getWorkOrdersForAward(id)]);setAward(a);setOrders(o);}catch(e){setError(e instanceof Error?e.message:"Unable to load tender award.");}}useEffect(()=>{void load();},[id]);if(!award)return <>{error?<div className="error-banner">{error}</div>:<div className="empty-state">Loading award...</div>}</>;const above=award.finalContractValue>award.tenderEstimatedValue;async function save(){try{const workOrderId=await createWorkOrder(id,{workOrderNumber:form.workOrderNumber,workOrderDate:form.workOrderDate,commencementDate:form.commencementDate||undefined,completionPeriodValue:Number(form.completionPeriodValue),completionPeriodUnit:form.completionPeriodUnit,performanceSecurityAmount:form.performanceSecurityAmount?Number(form.performanceSecurityAmount):undefined,performanceSecurityPercent:form.performanceSecurityPercent?Number(form.performanceSecurityPercent):undefined,securityDepositPercent:form.securityDepositPercent?Number(form.securityDepositPercent):undefined,retentionPercent:form.retentionPercent?Number(form.retentionPercent):undefined,agreementNumber:form.agreementNumber,agreementDate:form.agreementDate||undefined,remarks:form.remarks});setNotice("Work order draft created.");await load();location.assign("/work-orders/"+workOrderId);}catch(e){setError(e instanceof Error?e.message:"Unable to create work order.");}}return <><PageHeader eyebrow="Tender Award" title={award.awardNumber} description={award.contractorName}/>{error&&<div className="error-banner">{error}</div>}{notice&&<div className="success-banner">{notice}</div>}{above&&<div className="warning-banner">Final contract value is above the tender estimate.</div>}{!award.isL1&&<div className="warning-banner">Awarded contractor is not recorded as the sole lowest evaluated bidder.</div>}
<section className="section-band"><div className="section-title"><h2>Award Overview</h2><Link to={"/tenders/"+award.tenderId}>View Tender</Link></div><div className="detail-grid"><div><span>Award Date</span><strong>{String(award.awardDate)}</strong></div><div><span>DIET</span><strong>{award.dietName}</strong></div><div><span>Executing Agency</span><strong>{award.executingAgencyName}</strong></div><div><span>Work Package</span><strong>{award.workPackageCode}</strong></div><div><span>Contractor</span><strong>{award.contractorName}</strong></div><div><span>Rank</span><strong>{award.financialRank?"L"+award.financialRank:"—"}</strong></div></div></section>
<section className="section-band"><h2>Financial Summary</h2><div className="detail-grid"><div><span>Tender Estimate</span><strong>{formatIndianCurrency(award.tenderEstimatedValue)}</strong></div><div><span>Quoted Amount</span><strong>{formatIndianCurrency(award.quotedAmount)}</strong></div><div><span>Accepted Amount</span><strong>{formatIndianCurrency(award.acceptedTenderAmount)}</strong></div><div><span>Final Contract Value</span><strong>{formatIndianCurrency(award.finalContractValue)}</strong></div><div><span>Tender Saving</span><strong>{formatIndianCurrency(award.tenderSavingAmount)} ({award.tenderSavingPercent.toFixed(2)}%)</strong></div><div><span>Tender Excess</span><strong>{formatIndianCurrency(award.excessOverTenderEstimateAmount)} ({award.excessOverTenderEstimatePercent.toFixed(2)}%)</strong></div><div><span>Centre Share (60%)</span><strong>{formatIndianCurrency(award.contractCentralShare)}</strong></div><div><span>State Share (40%)</span><strong>{formatIndianCurrency(award.contractStateShare)}</strong></div></div></section>
{orders.length?<section className="section-band"><h2>Work Order</h2>{orders.map(o=><p key={o.id}><Link to={"/work-orders/"+o.id}>{o.workOrderNumber}</Link> — {o.status.replaceAll("_"," ")}</p>)}</section>:<section className="section-band agency-form"><div className="agency-form-wide section-title"><h2>Create Work Order</h2></div>{Object.entries({workOrderNumber:"Work Order Number",workOrderDate:"Work Order Date",commencementDate:"Commencement Date",completionPeriodValue:"Completion Period Value",performanceSecurityAmount:"Performance Security Amount",performanceSecurityPercent:"Performance Security %",securityDepositPercent:"Security Deposit %",retentionPercent:"Retention %",agreementNumber:"Agreement Number",agreementDate:"Agreement Date"}).map(([k,label])=><label key={k}>{label}<input type={k.toLowerCase().includes("date")?"date":k.includes("Amount")||k.includes("Percent")||k==="completionPeriodValue"?"number":"text"} value={form[k as keyof typeof form]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Completion Period Unit<select value={form.completionPeriodUnit} onChange={e=>setForm({...form,completionPeriodUnit:e.target.value as "days"|"months"})}><option value="days">Days</option><option value="months">Months</option></select></label><label className="agency-form-wide">Remarks<textarea value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></label><div className="form-actions"><button className="primary-button" onClick={()=>void save()}>Create Work Order Draft</button></div></section>}
<section className="section-band"><h2>Documents</h2><p className="muted-text">Award letter, agreement, performance security and work-order document uploads will be added in a future document phase.</p></section></>;}
