import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { RetenderAction } from "../components/RetenderAction";
import { TenderCorrigendaSection } from "../components/TenderCorrigendaSection";
import { useAuth } from "../contexts/AuthContext";
import { getTenderOperationalStatus, procurementMethodLabels, tenderStatusLabels, tenderTypeLabels } from "../constants/tenders";
import { cancelTender, getTenderById, markTenderForRetender, publishTender } from "../services/tenderService";
import { calculateFundingShare } from "../utils/fundingCalculations";
import { formatIndianCurrency } from "../utils/currency";
import { canEditTender, canPublishTender } from "../utils/tenderPermissions";
import type { Tender } from "../types";

const displayDate=(value:unknown,withTime=false)=>value&&typeof value==="object"&&"toDate" in value?(value as{toDate():Date}).toDate().toLocaleString("en-IN",withTime?undefined:{year:"numeric",month:"short",day:"numeric"}):"—";
export function TenderDetailPage(){const{id=""}=useParams(),{profile}=useAuth(),[item,setItem]=useState<Tender|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState("");const role=profile?.systemRole||profile?.role,admin=role==="scert_admin";async function load(){try{setItem(await getTenderById(id));}catch(e){setError(e instanceof Error?e.message:"Unable to load tender.");}}useEffect(()=>{void load();},[id]);async function act(kind:string){if(!item)return;setError("");try{if(kind==="publish")await publishTender(id);if(kind==="cancel"){const reason=window.prompt("Cancellation reason:")||"";if(!reason)return;await cancelTender(id,reason);}if(kind==="retender"){const reason=window.prompt("Re-tender remarks:")||"";await markTenderForRetender(id,reason);}setNotice("Tender status updated.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update tender.");}}if(!item)return <>{error?<div className="error-banner">{error}</div>:<div className="empty-state">Loading tender...</div>}</>;const shares=calculateFundingShare(item.estimatedTenderValue),operational=getTenderOperationalStatus(item);return <><PageHeader eyebrow="Tender detail" title={item.tenderTitle} description={item.tenderNumber||item.nitNumber||"Draft tender"}/>{error&&<div className="error-banner">{error}</div>}{notice&&<div className="success-banner">{notice}</div>}<div className="table-actions">{canEditTender(profile,item)&&<Link className="secondary-button" to={`/tenders/${id}/edit`}>Edit Tender</Link>}{canPublishTender(profile,item)&&<button className="primary-button" onClick={()=>void act("publish")}>Publish Tender</button>}{admin&&!['cancelled','retender_required'].includes(item.status)&&<button className="secondary-button danger-button" onClick={()=>void act("cancel")}>Record Tender Cancellation</button>}{admin&&item.status==="cancelled"&&<button className="secondary-button" onClick={()=>void act("retender")}>Mark Re-tender Required</button>}<RetenderAction tender={item}/></div><TenderCorrigendaSection tender={item} onChanged={()=>void load()}/>
<section className="section-band"><div className="section-title"><h2>Tender Overview</h2><Link to="/tenders">Back to register</Link></div><div className="detail-grid"><div><span>Tender Number</span><strong>{item.tenderNumber||"—"}</strong></div><div><span>NIT Number</span><strong>{item.nitNumber||"—"}</strong></div><div><span>Type</span><strong>{tenderTypeLabels[item.tenderType]}</strong></div><div><span>Procurement Method</span><strong>{procurementMethodLabels[item.procurementMethod]}</strong></div><div><span>Status</span><strong>{tenderStatusLabels[operational]}</strong></div></div></section>
<section className="section-band"><div className="section-title"><h2>Source Project</h2></div><div className="detail-grid"><div><span>DIET</span><strong>{item.dietName}</strong></div><div><span>Phase</span><strong>{item.phaseName}</strong></div><div><span>Executing Agency</span><strong>{item.executingAgencyName}</strong></div><div><span>Work Package</span><strong><Link to={`/work-packages/${item.workPackageId}`}>{item.workPackageCode}</Link></strong></div><div><span>Scope of Work</span><strong>{item.scopeOfWorkId||"Legacy package"}</strong></div></div></section>
<section className="section-band"><div className="section-title"><h2>Bidder Participation and Evaluation</h2><Link to={`/tenders/${id}/bids`}>Open Bidder Participation / Technical Evaluation</Link></div><p className="muted-text">Bid opening takes place on eProc Punjab. PMIS records the external opening events and subsequent evaluations for monitoring.</p><div className="detail-grid"><div><span>Technical Evaluation</span><strong>{item.technicalEvaluationStatus||"not started"}</strong></div><div><span>Technical Opening on eProc Punjab</span><strong>{item.technicalBidOpeningRecorded||item.technicalBidsOpenedAt?"Recorded":"Not recorded"}</strong></div><div><span>Financial Opening on eProc Punjab</span><strong>{item.financialBidOpeningRecorded||item.financialBidsOpenedAt?"Recorded":"Not recorded"}</strong></div><div><span>Financial Evaluation Status</span><strong>{(item.financialEvaluationStatus||"not_started").replaceAll("_"," ")}</strong></div></div><div className="table-actions"><Link className="secondary-button" to={`/tenders/${id}/financial-evaluation`}>Open Financial Evaluation</Link><Link className="secondary-button" to={`/tenders/${id}/comparative-statement`}>View Comparative Statement</Link></div></section>
<section className="section-band"><div className="section-title"><h2>eProc Punjab Technical Opening</h2></div><div className="detail-grid"><div><span>Scheduled Opening</span><strong>{displayDate(item.technicalBidOpeningDate,true)}</strong></div><div><span>Actual Opening</span><strong>{displayDate(item.technicalBidOpeningActualAt||item.technicalBidsOpenedAt,true)}</strong></div><div><span>Bids Received</span><strong>{item.technicalBidOpeningReceivedCount??"—"}</strong></div><div><span>Technical Bids Opened</span><strong>{item.technicalBidOpeningBidCount??"—"}</strong></div><div><span>Recorded By</span><strong>{item.technicalBidOpeningRecordedBy||item.technicalBidsOpenedBy||"—"}</strong></div><div><span>Recorded At</span><strong>{displayDate(item.technicalBidOpeningRecordedAt||item.technicalBidsOpenedAt,true)}</strong></div><div><span>eProc Reference</span><strong>{item.eProcTechnicalOpeningReference||"—"}</strong></div><div><span>Remarks</span><strong>{item.technicalBidOpeningRemarks||"—"}</strong></div></div></section>
<section className="section-band"><div className="section-title"><h2>eProc Punjab Financial Opening</h2></div><div className="detail-grid"><div><span>Scheduled Opening</span><strong>{displayDate(item.financialBidOpeningDate,true)}</strong></div><div><span>Actual Opening</span><strong>{displayDate(item.financialBidOpeningActualAt||item.financialBidsOpenedAt,true)}</strong></div><div><span>Qualified Bidders</span><strong>See financial evaluation</strong></div><div><span>Financial Bids Opened</span><strong>{item.financialBidOpeningBidCount??"—"}</strong></div><div><span>Recorded By</span><strong>{item.financialBidOpeningRecordedBy||item.financialBidsOpenedBy||"—"}</strong></div><div><span>Recorded At</span><strong>{displayDate(item.financialBidOpeningRecordedAt||item.financialBidsOpenedAt,true)}</strong></div><div><span>eProc Reference</span><strong>{item.eProcFinancialOpeningReference||"—"}</strong></div><div><span>Remarks</span><strong>{item.financialBidOpeningRemarks||"—"}</strong></div></div></section>
<section className="section-band"><div className="section-title"><h2>Award and Work Order</h2>{item.tenderAwardId?<Link to={"/tender-awards/"+item.tenderAwardId}>View Award</Link>:<Link to={"/tenders/"+id+"/award-recommendation"}>Select Successful Bidder / Create Award</Link>}</div><div className="detail-grid"><div><span>Award Status</span><strong>{(item.awardStatus||"not_started").replaceAll("_"," ")}</strong></div><div><span>Awarded Contractor</span><strong>{item.selectedContractorName||"—"}</strong></div></div></section>
<section className="section-band"><div className="section-title"><h2>Financial Summary</h2></div><div className="detail-grid"><div><span>Work Package Financial Basis</span><strong>{formatIndianCurrency(item.sourceFinancialBasis)}</strong></div><div><span>Estimated Tender Value</span><strong>{formatIndianCurrency(item.estimatedTenderValue)}</strong></div><div><span>Variation</span><strong>{formatIndianCurrency(item.valueVariationAmount)} ({item.valueVariationPercent.toFixed(2)}%)</strong></div><div><span>EMD</span><strong>{formatIndianCurrency(item.emdAmount||0)}</strong></div><div><span>Tender Fee</span><strong>{formatIndianCurrency(item.tenderFee||0)}</strong></div><div><span>Centre Share 60%</span><strong>{formatIndianCurrency(shares.centralShare)}</strong></div><div><span>State Share 40%</span><strong>{formatIndianCurrency(shares.stateShare)}</strong></div></div>{item.valueVariationRemarks&&<p><strong>Value variation remarks:</strong> {item.valueVariationRemarks}</p>}</section>
<section className="section-band"><div className="section-title"><h2>Timeline</h2></div><div className="detail-grid">{[["Notice",item.noticeDate],["Publication",item.publicationDate],["Download Start",item.documentDownloadStartDate],["Bid Submission Start",item.bidSubmissionStartDate],["Bid Submission End",item.bidSubmissionEndDate],["Pre-Bid Meeting",item.preBidMeetingDate],["Technical Bid Opening",item.technicalBidOpeningDate],["Financial Bid Opening",item.financialBidOpeningDate]].map(([label,value])=><div key={String(label)}><span>{String(label)}</span><strong>{displayDate(value)}</strong></div>)}</div></section>
<section className="section-band"><div className="section-title"><h2>Completion Period</h2></div><p>{item.completionPeriodValue?`${item.completionPeriodValue} ${item.completionPeriodUnit}`:"—"}</p></section><section className="section-band"><div className="section-title"><h2>Tender Portal</h2></div><div className="detail-grid"><div><span>Portal</span><strong>{item.tenderPortalName||"—"}</strong></div><div><span>Reference</span><strong>{item.tenderPortalReference||"—"}</strong></div><div><span>Link</span><strong>{item.tenderPortalUrl?<a href={item.tenderPortalUrl} target="_blank" rel="noreferrer">Open portal</a>:"—"}</strong></div></div></section><section className="section-band"><div className="section-title"><h2>Documents</h2></div><p className="muted-text">Tender document upload will be enabled in a later document-management phase.</p></section>
<section className="section-band"><div className="section-title"><h2>Review Remarks</h2></div><p><strong>Agency remarks:</strong> {item.internalRemarks||"—"}</p><p><strong>SCERT review remarks:</strong> {item.scertReviewRemarks||"—"}</p><p><strong>SCERT revision remarks:</strong> {item.revisionRemarks||"—"}</p></section>
<section className="section-band"><div className="section-title"><h2>Audit Information</h2></div><div className="detail-grid"><div><span>Created by</span><strong>{item.createdBy}</strong></div><div><span>Created at</span><strong>{displayDate(item.createdAt,true)}</strong></div><div><span>Submitted by</span><strong>{item.submittedBy||"—"}</strong></div><div><span>Submitted at</span><strong>{displayDate(item.submittedAt,true)}</strong></div><div><span>SCERT reviewer</span><strong>{item.reviewedBy||item.approvedForPublicationBy||"—"}</strong></div><div><span>SCERT approval date</span><strong>{displayDate(item.approvedForPublicationAt,true)}</strong></div><div><span>Published by</span><strong>{item.publishedBy||"—"}</strong></div><div><span>Published at</span><strong>{displayDate(item.publishedAt,true)}</strong></div></div>{item.status==="published"&&!item.approvedForPublicationAt&&<p className="muted-text">Legacy published tender — approval metadata unavailable</p>}</section></>}
