import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { getActivityMaster } from "../lib/firestore";
import { canAccessExecutionRecord } from "../services/accessScopeService";
import { getTendersForWorkPackage } from "../services/tenderService";
import { approveWorkPackageForTender, concurWorkPackageByDiet, finaliseWorkPackageByAgency, getWorkPackage, requestDietWorkPackageRevision, returnWorkPackageForRevision, reviewWorkPackage, sendWorkPackageToDiet, startDietWorkPackageReview, submitWorkPackageToScert } from "../services/workPackageService";
import { useAuth } from "../contexts/AuthContext";
import { canCreateTender } from "../utils/tenderPermissions";
import { tenderStatusLabels } from "../constants/tenders";
import { labelWorkCategory, workPackageStatusLabels } from "../constants/projectExecution";
import { formatIndianCurrency } from "../utils/currency";
import { getPackageFinancialBasis } from "../utils/fundingCalculations";
import type { ActivityMaster, Tender, WorkPackage } from "../types";

function displayTimestamp(value: unknown) {
  if (value && typeof value === "object" && "toDate" in value && typeof value.toDate === "function") return value.toDate().toLocaleString("en-IN");
  return "—";
}

export function WorkPackageDetailPage() {
  const { id = "" } = useParams();
  const { profile, accessScope } = useAuth();
  const [item, setItem] = useState<WorkPackage | null>(null), [activities, setActivities] = useState<ActivityMaster[]>([]), [tenders, setTenders] = useState<Tender[]>([]), [state, setState] = useState<"loading"|"loaded"|"not_found"|"access_denied"|"error">("loading");
  const [error,setError]=useState(""),[notice,setNotice]=useState("");
  const[reviewComment,setReviewComment]=useState("");const role=profile?.systemRole||profile?.role,canApprove=role==="scert_admin",dietUser=role==="diet_nodal_officer",agencyUser=role==="agency_user";
  async function load(){if(!accessScope){setState("loading");return;}setState("loading");setError("");try{const[data,master]=await Promise.all([getWorkPackage(id),getActivityMaster()]);if(!data){setItem(null);setState("not_found");return;}if(!canAccessExecutionRecord(accessScope,data)){setItem(null);setState("access_denied");return;}setItem(data);setActivities(master);setTenders(await getTendersForWorkPackage(id));setState("loaded");}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load the Work Package.");setState("error");}}
  useEffect(() => { void load(); }, [id, accessScope]);
  async function act(action:string){setError("");setNotice("");try{if(action==="send_diet")await sendWorkPackageToDiet(id);else if(action==="diet_review")await startDietWorkPackageReview(id);else if(action==="diet_revision")await requestDietWorkPackageRevision(id,reviewComment);else if(action==="diet_concur")await concurWorkPackageByDiet(id,reviewComment);else if(action==="finalise")await finaliseWorkPackageByAgency(id);else if(action==="submit_scert")await submitWorkPackageToScert(id);else if(action==="scert_review")await reviewWorkPackage(id);else if(action==="scert_return")await returnWorkPackageForRevision(id,reviewComment);else await approveWorkPackageForTender(id);setReviewComment("");setNotice(action==="approve"?"Package approved for tender. The executing agency may now create a Tender/NIT.":"Workflow updated.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to update the Work Package.");}}
  const selected = useMemo(() => activities.filter((activity) => item?.activityIds?.includes(activity.id)), [activities, item]);
  if(state==="loading")return <div className="empty-state">Loading work package...</div>;
  if(state==="not_found")return <><PageHeader title="Work package not found" description="The requested work package does not exist."/><Link to="/work-packages">Return to Work Packages</Link></>;
  if(state==="access_denied")return <><PageHeader title="Access denied" description="You are not authorised to access this work package."/><Link to="/work-packages">Return to Work Packages</Link></>;
  if(state==="error"||!item)return <><PageHeader title="Unable to load work package" description={error||"An unexpected error occurred."}/><Link to="/work-packages">Return to Work Packages</Link></>;
  return <><PageHeader eyebrow="Work package detail" title={item.packageTitle} description={item.packageCode}/>
    {notice&&<div className="success-banner">{notice}</div>}{error&&<div className="error-banner">{error}</div>}
    {(dietUser||canApprove)&&<label>Official review comment<textarea value={reviewComment} onChange={e=>setReviewComment(e.target.value)} placeholder="Required when requesting revision"/></label>}<div className="table-actions">{agencyUser&&["draft","agency_revision","diet_revision_requested","scert_revision_required","revision_required"].includes(item.status)&&<button className="secondary-button" onClick={()=>void act("send_diet")}>Send to DIET</button>}{dietUser&&item.status==="sent_to_diet"&&<button className="secondary-button" onClick={()=>void act("diet_review")}>Start DIET Review</button>}{dietUser&&["sent_to_diet","diet_review"].includes(item.status)&&<button className="secondary-button" onClick={()=>void act("diet_revision")}>Request Revision</button>}{dietUser&&["sent_to_diet","diet_review"].includes(item.status)&&<button className="primary-button" onClick={()=>void act("diet_concur")}>Concur</button>}{agencyUser&&item.status==="diet_concurred"&&<button className="primary-button" onClick={()=>void act("finalise")}>Finalise Package</button>}{agencyUser&&item.status==="ready_for_scert"&&<button className="primary-button" onClick={()=>void act("submit_scert")}>Submit to SCERT</button>}{canApprove&&["submitted_to_scert","submitted"].includes(item.status)&&<button className="secondary-button" onClick={()=>void act("scert_review")}>Start SCERT Review</button>}{canApprove&&["submitted_to_scert","scert_under_review","submitted","under_review"].includes(item.status)&&<button className="secondary-button" onClick={()=>void act("scert_return")}>Return for Revision</button>}{canApprove&&["submitted_to_scert","scert_under_review","submitted","under_review"].includes(item.status)&&<button className="primary-button" onClick={()=>void act("approve")}>Approve for Tender</button>}</div>
    <section className="section-band"><div className="section-title"><h2>Package Overview</h2><Link to="/work-packages">Back to register</Link></div><div className="detail-grid"><div><span>Code</span><strong>{item.packageCode}</strong></div><div><span>DIET</span><strong>{item.dietName}</strong></div><div><span>Phase</span><strong>{item.phaseName}</strong></div><div><span>Executing Agency</span><strong>{item.executingAgencyName}</strong></div><div><span>Category</span><strong>{labelWorkCategory(item.workCategory)}</strong></div><div><span>Status</span><strong>{workPackageStatusLabels[item.status]}</strong></div></div></section>
    <section className="section-band"><div className="section-title"><h2>DIET–Agency Handshake</h2><span>Revision {item.packageRevision||1}</span></div><div className="detail-grid"><div><span>Mutually Agreed Scope</span><strong>{item.scopeOfWorkId?"Linked":"Pending"}</strong></div><div><span>Agency Prepared</span><strong>{item.createdBy?"Complete":"Pending"}</strong></div><div><span>DIET Concurrence</span><strong>{item.handshake?.dietConcurrenceStatus||"Pending"}</strong></div><div><span>Agency Finalisation</span><strong>{item.handshake?.agencyFinalisationStatus||"Pending"}</strong></div><div><span>Handshake</span><strong>{item.handshake?.completed?"Complete":"Pending"}</strong></div><div><span>SCERT</span><strong>{["submitted_to_scert","scert_under_review","approved_for_tender"].includes(item.status)?workPackageStatusLabels[item.status]:"Pending submission"}</strong></div></div></section>
    <section className="section-band"><div className="section-title"><h2>Scope</h2></div><p>{item.packageDescription}</p><div className="activity-list">{selected.map((activity) => <div className="activity-row" key={activity.id}><span>{activity.serialNo}</span><strong>{activity.subActivity}</strong><code>{activity.code}</code></div>)}{!selected.length && <p className="muted-text">No activities selected.</p>}</div></section>
    <section className="table-wrap"><div className="section-title"><h2>Activity-wise Financial Allocation</h2></div>{item.activityAllocations?.length?<table><thead><tr><th>Activity</th><th>Agency Allocation</th><th>Package Allocation</th><th>Remaining after Package</th></tr></thead><tbody>{item.activityAllocations.map(x=><tr key={x.activityId}><td>{x.activityCode||"—"}<small>{x.activityName}</small></td><td>{formatIndianCurrency(x.agencyAllocation)}</td><td>{formatIndianCurrency(x.packageAllocatedAmount)}</td><td>{formatIndianCurrency(Math.max(0,x.agencyAllocation-x.packageAllocatedAmount))}</td></tr>)}</tbody></table>:<div className="warning-banner">Activity-wise financial breakdown required.</div>}</section>
    <section className="section-band"><div className="section-title"><h2>Financial Summary</h2></div><div className="detail-grid"><div><span>Estimated Cost</span><strong>{formatIndianCurrency(item.estimatedCost)}</strong></div><div><span>Administrative Approval</span><strong>{formatIndianCurrency(item.administrativeApprovalAmount)}</strong></div><div><span>Technical Sanction</span><strong>{formatIndianCurrency(item.technicalSanctionAmount)}</strong></div><div><span>Current Financial Basis</span><strong>{formatIndianCurrency(getPackageFinancialBasis(item))}</strong></div><div><span>Centre Share 60%</span><strong>{formatIndianCurrency(item.centralShareAmount)}</strong></div><div><span>State Share 40%</span><strong>{formatIndianCurrency(item.stateShareAmount)}</strong></div></div></section>
    <section className="section-band"><div className="section-title"><h2>Award and Work Order</h2>{item.tenderAwardId&&<Link to={"/tender-awards/"+item.tenderAwardId}>View Award</Link>}</div><div className="detail-grid"><div><span>Awarded Contractor</span><strong>{item.contractorName||"—"}</strong></div><div><span>Final Contract Value</span><strong>{formatIndianCurrency(item.finalContractValue||0)}</strong></div><div><span>Work Order</span><strong>{item.workOrderId?<Link to={"/work-orders/"+item.workOrderId}>{item.workOrderNumber}</Link>:"Pending"}</strong></div><div><span>Work Order Status</span><strong>{item.workOrderStatus?.replaceAll("_"," ")||"Not started"}</strong></div></div></section>
    <section className="section-band"><div className="section-title"><h2>Tender / NIT</h2>{item.status === "approved_for_tender" && !tenders.some(t => t.status !== "cancelled" && t.status !== "retender_required") && canCreateTender(profile, item.executingAgencyId) && <Link className="primary-button" to={`/tenders/new?workPackageId=${item.id}`}>Create Tender</Link>}</div>{tenders.length ? <table><thead><tr><th>Tender Number</th><th>Title</th><th>Estimated Value</th><th>Status</th></tr></thead><tbody>{tenders.map(t => <tr key={t.id}><td><Link to={`/tenders/${t.id}`}>{t.tenderNumber || t.nitNumber || "Draft"}</Link></td><td>{t.tenderTitle}</td><td>{formatIndianCurrency(t.estimatedTenderValue)}</td><td>{tenderStatusLabels[t.status]}</td></tr>)}</tbody></table> : <p className="muted-text">No tender has been created for this package.</p>}</section>
    <section className="section-band"><div className="section-title"><h2>Audit Information</h2></div><div className="detail-grid"><div><span>Created by</span><strong>{item.createdBy || "—"}</strong></div><div><span>Created at</span><strong>{displayTimestamp(item.createdAt)}</strong></div><div><span>Updated by</span><strong>{item.updatedBy || "—"}</strong></div><div><span>Updated at</span><strong>{displayTimestamp(item.updatedAt)}</strong></div></div></section>
  </>;
}
