import { useEffect, useState } from "react";
import { acceptArchitecturalDrawings, approveArchitecturalDrawings, releaseScopeToAgency, requestArchitectureScopeRevision, requestDrawingRevision, startArchitectureReview, startScertDrawingReview, submitDrawingsToScert, returnScertDrawingRevision } from "../services/scopeOfWorkService";
import { getDrawingPackages, issueDrawingRevision } from "../services/drawingPackageService";
import { getCommunications, sendCommunication } from "../services/communicationService";
import { getAttachments, uploadPdfAttachment } from "../services/documentService";
import type { AppUser, DocumentAttachment, DrawingPackage, OfficialCommunication, ScopeOfWork, SystemRole } from "../types";

export function ScopeArchitectureWorkflow({scope,profile,onChanged}:{scope:ScopeOfWork;profile:AppUser|null;onChanged:()=>Promise<void>}){
 const role=profile?.systemRole||profile?.role,[drawings,setDrawings]=useState<DrawingPackage[]>([]),[communications,setCommunications]=useState<OfficialCommunication[]>([]),[attachments,setAttachments]=useState<DocumentAttachment[]>([]),[comment,setComment]=useState(""),[subject,setSubject]=useState(""),[drawingNumber,setDrawingNumber]=useState(""),[drawingTitle,setDrawingTitle]=useState(""),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){const[d,c,a]=await Promise.all([getDrawingPackages(scope.id),getCommunications("scope_of_work",scope.id),getAttachments("scope_of_work",scope.id)]);setDrawings(d);setCommunications(c.sort((x,y)=>String(x.createdAt).localeCompare(String(y.createdAt))));setAttachments(a);}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Unable to load drawing workflow."));},[scope.id,scope.status]);
 async function upload(documentType:string,revision?:string){const ids:string[]=[];for(const file of files)ids.push((await uploadPdfAttachment(file,{entityType:"scope_of_work",entityId:scope.id,documentType,revision})).id);return ids;}
 async function run(action:string){setBusy(true);setError("");try{let attachmentIds:string[]=[];if(files.length)attachmentIds=await upload(action,scope.currentDrawingRevision);if(action==="architecture_review")await startArchitectureReview(scope.id);else if(action==="architecture_revision")await requestArchitectureScopeRevision(scope.id,comment);else if(action==="issue_drawings"){const next=`R${drawings.filter(x=>x.drawingDiscipline==="architectural").length}`;attachmentIds=await upload("architectural_drawing",next);await issueDrawingRevision(scope,{discipline:"architectural",drawingNumber,drawingTitle,attachmentIds,remarks:comment});}else if(action==="diet_revision")await requestDrawingRevision(scope.id,comment);else if(action==="diet_accept")await acceptArchitecturalDrawings(scope.id);else if(action==="submit_scert")await submitDrawingsToScert(scope.id);else if(action==="scert_review")await startScertDrawingReview(scope.id);else if(action==="scert_revision")await returnScertDrawingRevision(scope.id,comment);else if(action==="scert_approve")await approveArchitecturalDrawings(scope.id);else if(action==="release")await releaseScopeToAgency(scope.id);if(subject.trim()&&comment.trim())await sendCommunication({entityType:"scope_of_work",entityId:scope.id,toRole:action.startsWith("scert")?"scert_admin":role==="architecture_user"?"diet_nodal_officer":"architecture_user",communicationType:action,subject,message:comment,attachmentIds,relatedRevision:scope.currentDrawingRevision});setComment("");setSubject("");setFiles([]);await load();await onChanged();}catch(e){setError(e instanceof Error?e.message:"Unable to update drawing workflow.");}finally{setBusy(false);}}
 const fileById=new Map(attachments.map(x=>[x.id,x]));return <section className="section-band"><div className="section-title"><h2>Architecture Drawing Workflow</h2><span>{scope.status.replaceAll("_"," ")}</span></div>{error&&<div className="error-banner">{error}</div>}<div className="detail-grid"><div><span>Current Revision</span><strong>{scope.currentDrawingRevision||"Not issued"}</strong></div><div><span>DIET Acceptance</span><strong>{scope.dietAcceptedDrawingRevision===scope.currentDrawingRevision&&scope.currentDrawingRevision?"Accepted":"Pending"}</strong></div><div><span>SCERT Approval</span><strong>{scope.scertApprovedDrawingRevision===scope.currentDrawingRevision&&scope.currentDrawingRevision?"Approved":"Pending"}</strong></div><div><span>Released to Agency</span><strong>{scope.status==="released_to_executing_agency"?"Yes":"No"}</strong></div></div>
 {role==="architecture_user"&&["sent_to_architecture","architecture_review","architecture_revision_requested","drawing_revision_requested","scert_drawing_revision_required"].includes(scope.status)&&<div className="agency-form"><label>Drawing number<input value={drawingNumber} onChange={e=>setDrawingNumber(e.target.value)}/></label><label>Drawing title<input value={drawingTitle} onChange={e=>setDrawingTitle(e.target.value)}/></label><label className="agency-form-wide">Official comment<textarea value={comment} onChange={e=>setComment(e.target.value)}/></label><label className="agency-form-wide">PDF attachment(s)<input type="file" accept="application/pdf" multiple onChange={e=>setFiles([...e.target.files||[]])}/></label><div className="table-actions">{scope.status==="sent_to_architecture"&&<button disabled={busy} onClick={()=>void run("architecture_review")}>Start Review</button>}<button disabled={busy} onClick={()=>void run("architecture_revision")}>Request Clarification</button><button className="primary-button" disabled={busy} onClick={()=>void run("issue_drawings")}>Issue Drawings to DIET</button></div></div>}
 {role==="diet_nodal_officer"&&scope.status==="diet_drawing_review"&&<div className="agency-form"><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Comment<textarea value={comment} onChange={e=>setComment(e.target.value)}/></label><label>Optional annotated PDF<input type="file" accept="application/pdf" multiple onChange={e=>setFiles([...e.target.files||[]])}/></label><div className="table-actions"><button onClick={()=>void run("diet_revision")}>Request Drawing Revision</button><button className="primary-button" onClick={()=>void run("diet_accept")}>Accept Architectural Drawings</button></div></div>}{role==="diet_nodal_officer"&&scope.status==="diet_drawing_accepted"&&<button className="primary-button" onClick={()=>void run("submit_scert")}>Submit Drawings to SCERT</button>}
 {role==="scert_admin"&&["submitted_to_scert_for_drawing_approval","scert_drawing_review"].includes(scope.status)&&<div className="agency-form"><label>Official decision comment<textarea value={comment} onChange={e=>setComment(e.target.value)}/></label><label>Optional PDF<input type="file" accept="application/pdf" multiple onChange={e=>setFiles([...e.target.files||[]])}/></label><div className="table-actions">{scope.status==="submitted_to_scert_for_drawing_approval"&&<button onClick={()=>void run("scert_review")}>Start Drawing Review</button>}<button onClick={()=>void run("scert_revision")}>Return for Revision</button><button className="primary-button" onClick={()=>void run("scert_approve")}>Approve Architectural Drawings</button></div></div>}{role==="scert_admin"&&scope.status==="architectural_drawings_approved"&&<button className="primary-button" onClick={()=>void run("release")}>Release to Executing Agency</button>}
 <div className="section-title"><h2>Drawing Revisions</h2><span>Immutable history</span></div>{drawings.map(x=><div className="split-actions" key={x.id}><span>{x.drawingRevision} — {x.drawingTitle} ({x.status})</span><span>{x.attachmentIds.map(id=>fileById.get(id)).filter(Boolean).map(a=><a key={a!.id} href={a!.downloadUrl} target="_blank" rel="noreferrer">{a!.originalFileName}</a>)}</span></div>)}
 <div className="section-title"><h2>Correspondence</h2><span>{communications.length} entries</span></div>{communications.map(x=><article className="role-card" key={x.id}><strong>{x.fromOrganisation||x.fromRole} → {x.toOrganisation||x.toRole}</strong><small>{x.subject} · Revision {x.relatedRevision||"—"}</small><p>{x.message}</p></article>)}{!communications.length&&<p className="muted-text">No formal correspondence recorded.</p>}</section>;
}
